### ISSUE TITLE
The UITableView's line will cross the HUB, how to fix this?

### ISSUE THREAD

**Issue by jxdwinter** [jdg/MBProgressHUD#131]
![Screen Shot 2013-03-26 at 9 31 51](https://f.cloud.github.com/assets/1195524/300992/39333c00-95b5-11e2-9c34-bbd07dac2363.png)

Thank you very much.

**Comment by mrigdon** [comment]
this is not necessarily a fix - I actually need a colored separator

**Comment by matej** [comment]
Don't add the HUD to the table view directly. Use a superview of it.
