### ISSUE TITLE
MBProgressHUD does not hide when called

### ISSUE THREAD

**Issue by estock** [jdg/MBProgressHUD#133]
I have a method that is being called when video is done saving. When the video starts saving, I show the HUD, when the video is done, I call hide, but the HUD does not hide. If I let it run, eventually it hides, but not when I call it, Ive tried to add breakpoints, and it seems to get called, it just does not respond.

here is my complete function 
- (void)camCaptureComplete:(DIYCam *)cam withAsset:(NSDictionary *)asset
  {
  [VideoHUD hide:YES];
  [MBProgressHUD hideAllHUDsForView:self.view animated:YES];
  [self setupVideoPreview];
  [self.cam stopSession];
  }

**Comment by Ankish** [comment]
Swift 3 - If viewcontroller is a child controller (contained inside another controlelr ), it does not hide:
had to forcefully use the depriciated code to hide the loading

 func hideLoading(){
        delayWithSeconds(0.1, completion: {
        DispatchQueue.main.async {
            MBProgressHUD.hideAllHUDs(for: self.view, animated: true)
            if  MBProgressHUD.hide(for: self.view, animated: true) == false {
                //assert(false)
                print("cant hide")
            }
            }})
    }
