### ISSUE TITLE
Is that possible to change background-color of MBProgressHUD?

### ISSUE THREAD

**Issue by karthikeyanvijayan** [jdg/MBProgressHUD#14]
Hii ,

 Thanks for the awesome control , i had a UI which is dark design , so i need to apply the rounded corner with some other color ,

is that possible to customize background-color of the view?

**Comment by NikunjKumbhani** [comment]
Is there MBProgressHud available in swift classes ?
If Anyone Customised  please send me on 
@:- nikunj.kumbhani@elitechsystems.com
