### ISSUE TITLE
Why MBProgressHUD background task is stopped when app is sent to background?

### ISSUE THREAD

**Issue by quazarteam** [jdg/MBProgressHUD#196]
Hello!

I have a lengthy process which i start thru GCD with MBProgressHUD as it is described in your read.me. But, as soon as app enters background (via home button) then the whole task gets frozen and resumes itself as soon as app returns to foreground.
What should i do to have the task run even when app is in background ?

thanks you in advance

**Comment by Xlff** [comment]
but when my demo become active, the label of hud was dismissed,  the background view of hud is stall exist, i  click anywhere, no reaction.

**Comment by yas375** [comment]
> when my demo become active, the label of hud was dismissed, the background view of hud is stall exist, i click anywhere, no reaction.

For this part see #366.
