### ISSUE TITLE
Crash in viewDidAppear

### ISSUE THREAD

**Issue by egorzhdan** [jdg/MBProgressHUD#210]
My app crashes on setting labelText in viewDidAppear. Is it a bug or I'm doing something wrong?

![screen shot 2014-06-20 at 16 19 30](https://cloud.githubusercontent.com/assets/3801618/3339904/3bd4daf8-f875-11e3-9dd5-9185dd020f87.png)

(iOS SDK 8.0)

**Comment by matej** [comment]
Could this be a Swift bug?

**Comment by stevenlfg** [comment]
I also face this question.

**Comment by stevenlfg** [comment]
I alse face this problem.

**Comment by dxclancy** [comment]
Is this relevant?
http://stackoverflow.com/questions/24643522/fatal-error-unexpectedly-found-nil-while-unwrapping-an-optional-values

**Comment by matej** [comment]
This API has now been updated a bit. I hope that accessing `label` directly works better.
