### ISSUE TITLE
Landscape issue when "[[MBProgressHUD alloc] initWithView:[[UIApplication sharedApplication] keyWindow]]“

### ISSUE THREAD

**Issue by skywalkerlw** [jdg/MBProgressHUD#219]
in iOS8: Transforms are no longer applied to windows for rotation

![screenshot](https://cloud.githubusercontent.com/assets/2090084/3715553/ae6302fc-15e9-11e4-8063-c08b2a55a664.png)

**Comment by eikebartels** [comment]
this issue still exist on an iPad with iOS 8

**Comment by matej** [comment]
I don't see it in the demo, so you'll have to be more specific than that.

**Comment by matej** [comment]
Is ti perhaps the same problem as in #247?

**Comment by eikebartels** [comment]
Oh no it was my fault. It works fine now. Thanks
