### ISSUE TITLE
Background view still active when MBProgressHud is shown in IOS 8

### ISSUE THREAD

**Issue by kobluewater** [jdg/MBProgressHUD#220]
I show a MBProgressHud during data fetching.
However, user can still interact with the background view when MBProgressHud is shown, which lead to incorrect application behavior.
This doesn't happen in iOS7

**Comment by dataxpress** [comment]
I can confirm that this happens to me as well - when shown on a view belonging to a view controller that's pushed onto a navigation stack, the navigation bar buttons are still interactive. The solution is to present it on `self.navigationController.view` instead.

**Comment by matej** [comment]
This is normal. The navigation bar buttons are not part of the pushed view controller, but are, as you already figured out, part of the navigation controller view.
