### ISSUE TITLE
OS8 dimBackground device rotation broken

### ISSUE THREAD

**Issue by electricbolt** [jdg/MBProgressHUD#223]
Hi, 
On an iPad if I have dimBackground=YES and the HUD attached to the window, then when I rotate, the HUD popup rotates correctly, but the dim background does not.

To reproduce:
Using Xcode 6 beta 5 running on iPad 2 device with modifications to the HudDemo project as follows:
1. change HudDemoViewController.m showOnWindow method. Add HUD.dimsBackground=YES
2. change HudDemo target->General tab->Deployment info->Devices to 'Universal'.

Run. Select "On Window". Whilst HUD is shown, rotate device.
Cheers,
Matt.

**Comment by matej** [comment]
Should no longer be an issue with the latest version.
