### ISSUE TITLE
Rotation issue after keyboard was shown iOS 7.1

### ISSUE THREAD

**Issue by Kolineal** [jdg/MBProgressHUD#226]
Hi, 
I'm working on iPad app and it uses only landscape mode. I was trying to show a HUD and it was appearing sideways, version 0.9 seemed to fix it. But now I've faced another issue - HUD appears in the right orientation until the keyboard is shown. After it was shown, even if I hide it - the HUDs will appear sideways. App is running on iOS 7.1

The way I'm showing the HUD is
   `'MBProgressHUD *HUD = [MBProgressHUD showHUDAddedTo:[[[UIApplication sharedApplication] windows] lastObject] animated:YES];`

**Comment by matej** [comment]
Sorry for the long delay. Forgot about this one. If it's still any help - you're using it wrong. Adding the HUD to `[[[UIApplication sharedApplication] windows] lastObject]` means it will be added to the keyboard window when the keyboard is visible (that's a private `UITextEffectsWindow` instance). 

Add it to `[[UIApplication sharedApplication] keyWindow]` or a view and you should be good.
