### ISSUE TITLE
Multiple methods named “setProgress” found with mismatched result, parameter type or attributes

### ISSUE THREAD

**Issue by nonstriater** [jdg/MBProgressHUD#227]
I got a build error with that messsge When the env arm64, xcode6.0-DP, others OK! 

the error line is : 
       [(id)indicator setProgress:progress];

when I try  :
       [indicator performSelector:@selector(setProgress:) withObject:@(progress)];
that does't work!

so  I use the NSInvocation to solve this problem :

              NSMethodSignature *methodSignature = [[indicator class] instanceMethodSignatureForSelector:@selector(setProgress:)];
              NSInvocation *invocation = [NSInvocation invocationWithMethodSignature:methodSignature];
               invocation.target = indicator;
               invocation.selector = @selector(setProgress:);
              [invocation setArgument:&progress atIndex:2];// 注意从2开始
              [invocation invoke];

I want to ask If that ok or any more better way to forbid the errer?

**Comment by matej** [comment]
The progress is set through KVC now, so this should no longer be a problem.

**Comment by ripperhe** [comment]
Good!
