### ISSUE TITLE
Initial draw of progress bar much larger than progress indicated

### ISSUE THREAD

**Issue by dxclancy** [jdg/MBProgressHUD#246]
MBProgressHUDModeDeterminateHorizontalBar. When i set the first value on the progress bar, it draws progress from the beginning to just past the beginning curved end.  Then, for many subsequent updates it doesn't appear to progress because the initial draw is showing more progress than I actually set.  Does this make sense?

The same does not happen at the end.  It progressively fills little by little.

At a cursory glance at the code it looks like it might be using UIActivityIndicatorView?  Is this an issue with that control?

**Comment by matej** [comment]
This seems to have been done on purpose by the original author (@jejohnsonancestry). Here's the relevant code: https://github.com/jdg/MBProgressHUD/commit/c84bea7b7b68#diff-77bb4d01f867ea1f44d816a66131d999R1002 

I guess it could make sense to make this more similar to how the right side is handled: https://github.com/jdg/MBProgressHUD/commit/c84bea7b7b68#diff-77bb4d01f867ea1f44d816a66131d999R975

**Comment by dxclancy** [comment]
I'm not sure what the motivation for doing it on purpose is, as I don't see any comments about it?  For my uses, it just makes it look like no progress is occurring when using lots of progress steps.

**Comment by matej** [comment]
Should no longer be an issue with the redesigned progress bar.
