### ISSUE TITLE
Rotation in iOS8 are still broken

### ISSUE THREAD

**Issue by GusevAndrey** [jdg/MBProgressHUD#247]
There still need rotation handling if superview is window without rootViewController.

As far as I managed to see windows in ios8 change frames only if has a rootViewController set, and do not change if it hasn't set.
If showHUDAddedTo: myOverlayWindow that hasn't set a rootViewController no HUD rotation happens.

So updated shouldPerformOrientationTransform should look like this:

```ObjC
- (BOOL)shouldPerformOrientationTransform {
	BOOL isPreiOS8 = NSFoundationVersionNumber < kCFCoreFoundationVersionNumber_iOS_8_0;
    
    // prior to iOS8 code needs to take care of rotation if it is being added to the window or if window hasn't rootViewController in iOS8
    BOOL isSuperviewWindow = [self.superview isKindOfClass:[UIWindow class]];    
    return (isPreiOS8 && isSuperviewWindow) || (isSuperviewWindow && [(UIWindow *)self.superview rootViewController] == nil);
}
```

But there is more.
Inside setTransformForCurrentOrientation not only transformation occurs, but bounds changes, which affect transform animation so HUD's labels and activityIndicator are moving from side to their places while rotation.

Bound changing need to update dimBackground size, which also conflicts with animation: bound changes occurs after and without animation.
Removing bounds updates doing well with HUD rotation animation. But dimBackground do not changes it's size.

What if change the hierarchy little bit?
In fact, if compose HUD with all labels and indicators with one small view placed at superview's centre point and apply rotation only to it, but not the entire view. 
DimBackground drawn once do not changes it's size or rotates at all (radial gradient are the same as long as the HUD's centre at the same point).

Looks like it may help.

**Comment by matej** [comment]
@CrimsonChris so you used the `shouldPerformOrientationTransform` modifications from @GusevAndrey and added a `layoutSubviews` call? Where exactly did you add it? 

Refactoring the bezel to be a new subview would probably help with this issue, ad some others as well.

**Comment by objectiveSee** [comment]
I just updated from 0.8 to 0.9 via Cocoapods and the orientation issue has been resolved.  I noticed there is a fork at the moment on this repo.  Cocoapods uses http://cocoadocs.org/docsets/MBProgressHUD/0.9/ which is the "official" library (apparently): https://github.com/matej/MBProgressHUD

**Comment by matej** [comment]
I pretty much try keep those two in sync since they are both relatively popular. It shouldn't make any difference which URL is used.
