### ISSUE TITLE
MBProgressHUDModeDeterminate progress fill color

### ISSUE THREAD

**Issue by Thomas101** [jdg/MBProgressHUD#253]
I've found that if you try to customize the `MBRoundProgressView` colours there's an inconsistency when  using the `MBProgressHUDModeDeterminate` mode in that you can customize the outer circle but not the fill for it. (see below, the pie slice is still white)
![untitled](https://cloud.githubusercontent.com/assets/103586/5227295/509037bc-76f1-11e4-9423-2fe7dedb4c30.png)

As a fix, I suggest that in the `drawRect:` method of `MBRoundProgressView` the fill color is changed to be the same as the progress tint color.

```objc
		// Draw background
		[_progressTintColor setStroke];
		[_backgroundTintColor setFill];
		CGContextSetLineWidth(context, 2.0f);
		CGContextFillEllipseInRect(context, circleRect);
		CGContextStrokeEllipseInRect(context, circleRect);
		// Draw progress
		CGPoint center = CGPointMake(allRect.size.width / 2, allRect.size.height / 2);
		CGFloat radius = (allRect.size.width - 4) / 2;
		CGFloat startAngle = - ((float)M_PI / 2); // 90 degrees
		CGFloat endAngle = (self.progress * 2 * (float)M_PI) + startAngle;
-		CGContextSetRGBFillColor(context, 1.0f, 1.0f, 1.0f, 1.0f); // white
+        [_progressTintColor setFill];
		CGContextMoveToPoint(context, center.x, center.y);
		CGContextAddArc(context, center.x, center.y, radius, startAngle, endAngle, 0);
		CGContextClosePath(context);
		CGContextFillPath(context);
```

**Comment by matej** [comment]
Fixed in 6033a0b1ada89605a146fa277347e16eb63ca1cb. Sorry for the long wait.
