### ISSUE TITLE
MBProgressHUD with navigationController?.pushViewController

### ISSUE THREAD

**Issue by netwire88** [jdg/MBProgressHUD#255]
Is there a way that I can display MBProgressHUD while the view is being transitioned from one view to another?  For example?

```
MBProgressHUD.showHUDAddedTo(view, animated: true)
navigationController?.pushViewController(destinationVC, animated: true)
```

This doesn't seem to work, should I be adding any other code in the view being loaded or while the view is disappearing, such as:

```
    override func viewDidDisappear(animated: Bool) {
        MBProgressHUD.hideHUDForView(view, animated: true)
    }
```

**Comment by matej** [comment]
Add the HUD to `navigationController.view` or to `view.window` instead of directly to the `view`.
