### ISSUE TITLE
MBProgressHUD memory leaks

### ISSUE THREAD

**Issue by leiyong316** [jdg/MBProgressHUD#256]
Found that memory is not released, it will crash the program runtime.

![untitled](https://cloud.githubusercontent.com/assets/2143362/5642635/f2f54438-9687-11e4-8140-be5d4e382a7f.gif)

**Comment by leiyong316** [comment]
Memory only to rise,  not released

**Comment by KaiCode2** [comment]
huh, I'll get on it now.

**Comment by matej** [comment]
Set a breakpoint in `- [MBProgressHUD dealloc]`. Does it get called? It does for me.

**Comment by leiyong316** [comment]
@matej  no call dealloc

**Comment by matej** [comment]
Are you using ARC? If you can come up with a failing sample project I can take a look at it. Like I said, I don't see the same behavior locally.

**Comment by leiyong316** [comment]
@matej   yes, using ARC ,   i can come up with a failing sample project,  project how to you?   you email?

**Comment by matej** [comment]
Zip it and upload it to a file sharing service like dropbox or cloudapp. Just past the link here.

**Comment by leiyong316** [comment]
China exist GFW, dropbox not on.
BaiDu Cloud service
http://pan.baidu.com/s/16hxOq

thanks

**Comment by matej** [comment]
The problem you're seeing has been fixed in https://github.com/jdg/MBProgressHUD/commit/cb56321f4063995a3cc93f7e353935e22ad58236. Just use the latest version.

**Comment by leiyong316** [comment]
@matej  Thanks.
But, i useing cocoapods
my 'Podfile' file pod 'MBProgressHUD', '~> 0.9'
not latest version why?

do version 0.9 updated to cocoapods?

**Comment by matej** [comment]
0.9 has the change https://github.com/jdg/MBProgressHUD/blob/0.9/MBProgressHUD.m#L118

I'm not sure why it would not show up for you.

**Comment by matej** [comment]
Ah I see. The fork that is used in cocoapods does not have that change in 0.9 (https://github.com/matej/MBProgressHUD/blob/0.9/MBProgressHUD.m). 

Just manually set `hud.removeFromSuperViewOnHide = YES;` after showing it for the time being. I'll update cocoa-pods when I find a bit of time.

**Comment by leiyong316** [comment]
ok. very thanks, finally solved The problem
