### ISSUE TITLE
MBProgressHUD got a Crash 

### ISSUE THREAD

**Issue by arishanapalli** [jdg/MBProgressHUD#258]
Hi
Team,

Since i am using this MBProgressHUD i found a crash when using the in mobile application.
-(void)onClick{
        [NSThread detachNewThreadSelector:@selector(showLoader) toTarget:self withObject:nil];
//Code something
}
-(void)showLoader {
    MBProgressHUD *hud = [MBProgressHUD showHUDAddedTo:self.view animated:YES];
    hud.labelText = @"Please Wait";
}
-(void)responseDate:(id)response{
    NSLog(@"Response %@",response);    
    [MBProgressHUD hideHUDForView:self.view animated:YES];
/ /Do something
}
            // Update to indeterminate indicator
            [indicator removeFromSuperview];
            self.indicator = MB_AUTORELEASE([[UIActivityIndicatorView alloc]
                                             initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleWhiteLarge]);
            [(UIActivityIndicatorView *)indicator startAnimating];
            [self addSubview:indicator];

            self.indicator = MB_AUTORELEASE([[UIActivityIndicatorView alloc]
Its happens on occasionally (not on regular internal). 

 .

**Comment by matej** [comment]
What is the crash? Please fix the code formatting as well.

**Comment by arishanapalli** [comment]
Sorry, I did not save the crash log.
But the crash is happening rarely.  If i am calling it continuously, showLoader method and  responseDate method then its crashing.
i.e, 

-(void)showLoader {
MBProgressHUD *hud = [MBProgressHUD showHUDAddedTo:self.view animated:YES];
hud.labelText = @"Please Wait";
}
-(void)responseDate:(id)response{
[MBProgressHUD hideHUDForView:self.view animated:YES];
/ /Do something
}

project runs  on XCode version 6.1.1. ARC

**Comment by matej** [comment]
I can't see anything wrong with that code.

**Comment by arishanapalli** [comment]
I had a crash, but its happens very rarely.

**Comment by iosdevelopersravan** [comment]
App Crashing in this ilne
effectView.frame = self.bounds;

Method name "updateForBackgroundStyle"

Please guide me
