### ISSUE TITLE
Still alive? 

### ISSUE THREAD

**Issue by eikebartels** [jdg/MBProgressHUD#259]
Hello,

is this repo still alive?? The last commit is 3 month ago and there are heaps of pull requests...

If you @jdg need any help to keep care of this project. I reckon we will easily someone. It would be sad if a nice lib like this one to pass out of mind

**Comment by matej** [comment]
Yes it is. Just a bit low on time. A bunch of those PRs are actually just things that need to be closed. The last commit is from end of December which isn't exactly 3 months.

**Comment by eikebartels** [comment]
Ok thanks for the answer!
