### ISSUE TITLE
Undefined Symbols for architecture x86_64

### ISSUE THREAD

**Issue by arthankamal** [jdg/MBProgressHUD#264]
My podfile

`platform : ios, '7.0'
pod 'AFNetworking'
pod 'MBProgressHUD', '~>0.8'
`

I'm getting an Undefined symbols for architecture x86_64

`Undefined symbols for architecture x86_64:<br>
  "_OBJC_CLASS_$_MBProgressHUD", referenced from:<br>
      objc-class-ref in ViewController.o<br>
ld: symbol(s) not found for architecture x86_64<br>
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by matej** [comment]
I don't know what's up here. I don't think it's na issue with MBProgressHUD itself. It's more likely a problem with cocoa-pods or your project configuration.

**Comment by NikolaySohryakov** [comment]
@arthankamal did you solve this issue?

**Comment by sukithakc** [comment]
Im also getting this issue. Any fix anybody?

**Comment by matej** [comment]
Looks like a cocoa pods issue to me.

https://github.com/CocoaPods/CocoaPods/issues/2545
http://stackoverflow.com/questions/19213782/undefined-symbols-for-architecture-arm64
