### ISSUE TITLE
NSAssert in show or hide

### ISSUE THREAD

**Issue by monishsyed** [jdg/MBProgressHUD#265]
Hey,

It'll be great to put some non main queue assertion in the show and hide methods of MBProgressHUD. Lot of people out there are using third part libraries that don't guarantee the callback to be on main queue. Usually the hide method gets called from a non-main thread and eventually something bad happens that is hard to catch if the assertions are not there. I'll put up a PR soon for this. Let me know your feedback for the same.

**Comment by joemasilotti** [comment]
Shot in the dark here, but does this have anything to do with the library raising an exception on [MBProgressHUD.m line 307](https://github.com/jdg/MBProgressHUD/blob/master/MBProgressHUD.m#L307)?

` -[MBProgressHUD autocapitalizationType]: unrecognized selector sent to instance 0x7fd25dd1d2c0`

**Comment by matej** [comment]
Sounds reasonable. Added in 7782822.
