### ISSUE TITLE
A button to Cancel the task.

### ISSUE THREAD

**Issue by douglasjunior** [jdg/MBProgressHUD#270]
Do you intend to implement a Button to be able to cancel the task?

I found this pullrequest: https://github.com/jdg/MBProgressHUD/pull/230

But he has not yet been merged.

**Comment by semerda** [comment]
I like this. Would also like to know :)

**Comment by matej** [comment]
Yeah, I have it on the list for https://github.com/matej/MBProgressHUD/pull/68. Not yet sure how to best design that though.

**Comment by gabosgab** [comment]
+1!!

**Comment by magellan314** [comment]
I already did this on MBProgressHUD when I wasn't updating for cocoa pods. Could you implement something similar?

Basically, added another button which was incremented in the "layoutSubviews" method. Then, I connected an action within MBProgressHUD which could callback to my class to notify a button on MBProgressHUD was pressed:

- (void)formButtonTapped:(id)sender {
    if ([delegate respondsToSelector:@selector(formButtonWasPressed:)]) {
        [delegate performSelector:@selector(formButtonWasPressed:) withObject:self.formButton];
    }
}

**Comment by matej** [comment]
Added in the latest version.
