### ISSUE TITLE
Progress Doesn't Update - Swift

### ISSUE THREAD

**Issue by mdaymond** [jdg/MBProgressHUD#271]
I have the following method below that is getting some errors when I attempt to update.   Note: This method below is called from the main thread...

I am getting the following error: <Error>: void CGPathAddArc(CGMutablePathRef, const CGAffineTransform *, CGFloat, CGFloat, CGFloat, CGFloat, CGFloat, bool): invalid value for start or end angle

```
    func update(){
        var hud = MBProgressHUD.showHUDAddedTo(self.view, animated: true)
        hud.labelText = "Please wait..."
        hud.mode = MBProgressHUDMode.Determinate

        if (uploadSize == amountUploaded){

        }
        else{
            println("the amount: \(Float(uploadSize - amountUploaded))")
            hud.progress = Float(uploadSize - amountUploaded)
        }
    }
```

It is called from another method like this:

```
dispatch_sync(dispatch_get_main_queue(), { () -> Void in
                self.amountUploaded = totalBytesSent
                self.uploadSize = totalBytesExpectedToSend;
                self.update()
                
            })
```

**Comment by matej** [comment]
Perhaps `Float(uploadSize - amountUploaded)` is negative.

**Comment by mdaymond** [comment]
yes.. my mistake.  thanks.
