### ISSUE TITLE
Use of unresolved identifier MBProgressHUDModeCustomView

### ISSUE THREAD

**Issue by netwire88** [jdg/MBProgressHUD#273]
Hi,
I've recently upgraded to `MBProgressHUD 0.9.1`, I have code that looked like this that used to build successfully:
```
            MBProgressHUD.hideHUDForView(view, animated: true)
            let hud = MBProgressHUD.showHUDAddedTo(view, animated: true)
            hud.customView = UIImageView(image: UIImage(named: "CheckmarkHUD"))
            hud.mode = MBProgressHUDModeCustomView
            hud.color = UIColor.applicationBlueColor()
            hud.labelText = message
```
But now I get error `Use of unresolved identifier MBProgressHUDModeCustomView` on line `hud.mode = MBProgressHUDModeCustomView` when trying to build. I checked the documentation on MBProgressHUD Github and the examples are still using `MBProgressHUDModeCustomView`. I'm on Xcode 6.3 and Swift 1.2.

**Comment by batical** [comment]
I switch to xcode 6.3 today got same issue with indeterminate
*As I am using cocoapods, I update it using the last beta version (gem install cocoapods --pre)
* I update using pod install command

Not sure those 2 lines were required but I remove the build replacing
 hud.mode = MBProgressHUDModeIndeterminate by hud.mode = .Indeterminate

You should try hud.mode = .CustomView. Got no build error but cannot confirm the behavior is the same

**Comment by zhouhaibing089** [comment]
`hud.mode = MBProgressHUDMode.CustomView` should work.

**Comment by matej** [comment]
@netwire88 Did that fix the issue?
