### ISSUE TITLE
quick show:YES after hide:YES does not have an effect

### ISSUE THREAD

**Issue by nickbit** [jdg/MBProgressHUD#276]
Hello,
it seems that when trying to show the HUD and it is still in the hide process from a previous hide it does not show. Changing the animated parameter to NO, solves this, but apparently not the way it should.

**Comment by fergalrooney** [comment]
I may be seeing something similar in version 0.9.1. When I add the progress view using      <code>MBProgressHUD.showHUDAddedTo(self.view, animated: false)</code>
and retain the returned reference, calling instance methods hide hides the view successfully, but when I call the show instance method, the view never shows. I reverted back to version 0.9.0 and it works fine again.

**Comment by ekimovnikolay** [comment]
Got the same problem. 
in 0.9.1 line [self setNeedsDisplay] was removed from method - (void)show:(BOOL)animated ; And smth else was changed. Smth that breaks the functionality.

**Comment by matej** [comment]
If you're using `showHUDAddedTo...` it's not a bug. See #279.

**Comment by gerchicov-bp** [comment]
the "solution" doesn't work for complex work
