### ISSUE TITLE
HUD non visible after alertView clickedButtonAtIndex IOS 7

### ISSUE THREAD

**Issue by marinotws** [jdg/MBProgressHUD#277]
Hi, if i have 

     - (void)alertView:(UIAlertView *)alertView clickedButtonAtIndex:(NSInteger)buttonIndex
    {
         [alertView dismissWithClickedButtonIndex:buttonIndex animated:YES];
         [self performSelector:@selector(cmdRename:) withObject:[alertView textFieldAtIndex:0].text afterDelay:0.5];
         ......
     }

next i call 

    self.hud = [MBProgressHUD showHUDAddedTo:[UIApplication sharedApplication].keyWindow animated:NO];
    ....

HUD is not visible .. ? why ?

thanks

**Comment by matej** [comment]
That's not enough context to know what's going on. And also not a bug report but support request.

**Comment by matej** [comment]
Is the same code working on iOS 8?

**Comment by marinotws** [comment]
yes! in OS8 no problem !

**Comment by matej** [comment]
Check if [UIApplication sharedApplication].keyWindow is perhaps nil. Can't tell much more from what you provided.

**Comment by marinotws** [comment]
this is my code : 

- (void)visibleHudIndeterminate:(NSString *)title withButton:(NSString *)buttonTitle
{    
    if ([UIApplication sharedApplication].keyWindow) self.hud = [MBProgressHUD showHUDAddedTo:[UIApplication sharedApplication].keyWindow animated:NO];
    else return;
    
    if (!self.hud) return;
    
    self.hud.removeFromSuperViewOnHide = YES;
    self.hud.mode = MBProgressHUDModeIndeterminate;
    self.hud.delegate = self;
    if ([title length]) self.hud.labelText = NSLocalizedString(title, nil);
    if ([buttonTitle length]) self.hud.buttonTitle = NSLocalizedString(buttonTitle, nil);
    self.hud.hidden = NO;
}

**Comment by marinotws** [comment]
[UIApplication sharedApplication].keyWindow is NOT nil

**Comment by marinotws** [comment]
the problem is only next call alertView ...

**Comment by matej** [comment]
Can you attach a sample project that exhibits the issue?

**Comment by marinotws** [comment]
i have discovered the problem ... the problem isn't of MBProgressHUD but in a contributory cause of factors ... thanks !!
