### ISSUE TITLE
hide a hub and then show immediately but can not see it

### ISSUE THREAD

**Issue by bluesky0109** [jdg/MBProgressHUD#281]
self.aHub = [[MBProgressHUD alloc] initWithView:self.view];
    self.aHub.mode = MBProgressHUDModeText;
    self.aHub.labelText = @"some hub xxx";
    [self.view addSubview:self.aHub];
    [self.aHub show:YES];

    dispatch_time_t popTime = dispatch_time(DISPATCH_TIME_NOW, 2 * NSEC_PER_SEC);
    dispatch_after(popTime, dispatch_get_main_queue(), ^(void){
        
        [self.aHub hide:YES];
        
//        NSLog(@"sup>>%@",self.aHub.superview);
//        sleep(2);
        
        self.aHub.labelText = @"dkflskjlfls";
        [self.aHub show:YES];
        
    });

I can not see second hub

**Comment by matej** [comment]
http://stackoverflow.com/a/5834571/88854

**Comment by gerchicov-bp** [comment]
Doesn't work! It just makes the bug appear less often
