### ISSUE TITLE
HUD crashes some time

### ISSUE THREAD

**Issue by iraj-wisilica** [jdg/MBProgressHUD#282]
MBProgressHUD.m line 573
-[MBProgressHUD layoutSubviews]  causes crash some times

**Comment by matej** [comment]
You'll have to be more specific than that. MBProgressHUD.m:573 is just `labelF.origin.x = round((bounds.size.width - labelSize.width) / 2) + xPos;` on the latest version. I don't really see what could go wrong here on its own.

**Comment by ratishmah** [comment]
I am also facing this same issue on iOS version 8. Any solution?
<img width="940" alt="screen shot 2015-09-10 at 11 55 52 am" src="https://cloud.githubusercontent.com/assets/12071455/9781531/1463b4e6-57b3-11e5-9bd1-5e91f585754b.png">

**Comment by matej** [comment]
Will hopefully be fixed once https://github.com/matej/MBProgressHUD/pull/68 gets merged in. The layout code changed completely.

**Comment by matej** [comment]
Hopefully this is no longer an issue. Reopen if otherwise.

**Comment by jkyin** [comment]
@matej Today, it crashed again. So sad. But can not reproduction.

You can see this http://crashes.to/s/e5d0f05960e
