### ISSUE TITLE
MBProgresshud installed but give error

### ISSUE THREAD

**Issue by badalpub1991** [jdg/MBProgressHUD#283]
i have installed 2 pods `MBProgessHUD` and `PEPhotocropEditor` it's working correctly till now but suddenly i got error for `MBProgressHUD.h` file not available. and i tried it with `pod update` and again `pod install` command but still not able to solve the problem. when i fier both the command terminal stucked at 

> Analysing dependencies.

![Stuck at Analysing dependencies][1]

and pods are looking in red color.

![pods in red color][2]

  [1]: http://i.stack.imgur.com/AnfnU.png
  [2]: http://i.stack.imgur.com/8NSLU.png

**Comment by matej** [comment]
This looks like a cocoapods issue, not an issue with MBProgressHUD.

**Comment by badalpub1991** [comment]
@matej :- thanks for the replay. true it was cocoapods error . solved in  this way.

My problem is solved with following procedure.

1) Take Backup of your Project to other place.

2) open Terminal , and go to your project directory with `cd` command.

3) first type this command 
         

setup you pod:

    $ pod repo remove master
    $ pod setup
    $ pod install

 
**Note**  
        It takes time. so, don't panic wait for few minuts. 

**EDIT :-**
    After completing this all if you find error like 
    

> MBProgressHUD.h file not found ( any of pod related header file)

you need to follow this procedure also.

you need to Check if the pod header files are correctly symlinked in Pods/Headers. (All imagae give with correct setting)



 [WIKI ][1] or [Cocoapods Troubleshooting] [2] gives explaination in brief. 

1) If something doesn’t seem to work, first of all ensure that you are not completely overriding any options set from the Pods.xcconfig file in your project’s build settings. To add values to options from your project’s build settings, prepend the value list with $(inherited).

   ![$(inherited)][3]

2) If Xcode can’t find the headers of the dependencies:

 Check if the pod header files are correctly symlinked in Pods/Headers and you are not overriding the HEADER_SEARCH_PATHS (see #1).
   Make sure your project is using the Pods.xcconfig. To check this select your project file, then select it in the second pane again and open the Info section in the third pane. Under configurations you should select Pods.xcconfig for each configurations requiring your installed pods.

  ![Make sure your project is using correct file][4]


 If Xcode still can’t find them, as a last resort you can prepend your imports, e.g. #import "Pods/SSZipArchive.h"


**Don't need to include below step if only Headerfile missing Error.**

Below line and image give for reference if some one can't find proper option.


3) If you're getting **errors** about unrecognized C compiler command line options, e.g. **cc1obj: error: unrecognized command line option "-Wno-sign-conversion"**:

 Make sure your project build settings are configured to use "**Apple LLVM compiler**" (clang)


 ![Project Build setting are configured to use "Apple LLVM compiler" ][5]
    Are you setting the CC, CPP or CXX environment variable, e.g. in your ~/.profile? This may interfere with the Xcode build process. Remove the environment variable from your ~/.profile.
  ~/ .profile location

    1)open Settings > General
    2) Scroll to the bottom and open Profiles. If you do not see a "Profiles" section, you do not have a configuration profile installed.
In the "Profiles" section, select the profile you wish to remove.


4) If Xcode complains when linking, e.g. Library not found for -lPods, it doesn't detect the implicit dependencies:

    Go to Product > Edit Scheme
    Click on Build
       ![Edit scheme][6]
    Add the Pods static library, and make sure it's at the top of the list
    Clean and build again.
    If that doesn't work, verify that the source for the spec you are trying to include has been pulled from github. Do this by looking in 

<Project Dir>/Pods/<Name of spec you are trying to include>. If it is empty (it should not be), verify that the ~/.cocoapods/master/<spec>/<spec>.podspec has the correct git hub url in it.
    If still doesn't work, check your XCode build locations settings. Go to Preferences -> Locations -> Derived Data -> Advanced and set build location to "Relative to Workspace".

Xcode Build Location Setting:-
    If you tried to submit app to App Store, and found that "Product" > "Archive" produce nothing in "Organizer":
        In Xcode "Build Settings", find "Skip Install". Set the value for "Release" to "NO" on your application target. Build again and it should work.


        


  [1]: https://github.com/CocoaPods/CocoaPods/wiki/Creating-a-project-that-uses-CocoaPods/2c6eb4b8b3a169d350891ce7005f9715f6a6ec4d
  [2]: https://guides.cocoapods.org/using/troubleshooting.html
  [3]: http://i.stack.imgur.com/lwyFX.png
  [4]: http://i.stack.imgur.com/J6jRB.png
  [5]: http://i.stack.imgur.com/UzF73.png
  [6]: http://i.stack.imgur.com/cvJOq.png
