### ISSUE TITLE
IOS7 rotation issue in UIWindow

### ISSUE THREAD

**Issue by winddpan** [jdg/MBProgressHUD#284]
UIWindow *topWindow = [[[UIApplication sharedApplication] windows] lastObject];

When I modal a viewController and added a hud on topWindow ( device on landscape), the hud rotation will be incorrect. 
Meanwhile, I opend the keyboard!

**Comment by matej** [comment]
Don't add it to `[[[UIApplication sharedApplication] windows] lastObject]`. This could very well be a system created temporary window.
