### ISSUE TITLE
MBBarProgressView position below detailTextLabel

### ISSUE THREAD

**Issue by vijaydogra** [jdg/MBProgressHUD#288]
I was trying to play around with some modification of code to move the Progressbar shown at bottom of detailTextLabel instead of showing it above textLabel.

Is it readily available, or should I continue to play with frames position?

**Comment by matej** [comment]
Yeah, yo need to subclass and override `layoutSubviews`. Might get a bit more straightforward once auto layout lands (https://github.com/matej/MBProgressHUD/pull/68).

**Comment by vijaydogra** [comment]
Ok, perfect. Will continue playing with layoutSubviews
