### ISSUE TITLE
"done" animation callback always gets run, even if HUD has since been re-shown.

### ISSUE THREAD

**Issue by cellularmitosis** [jdg/MBProgressHUD#292]
If you hide a HUD, and then re-show that same HUD during its 0.3 second hide animation, the hide animation completion callback ("done") doesn't get cancelled.  This creates the following sequence of events:

* Hide called.  Start the hide animation.
* Show called.  Start the show animation.
* Hide animation finishes.  HUD is removed from superview.

Even though the end result was that you wanted the HUD to remain on-screen, the "done" handler effectively clobbers your call to re-show the HUD.

The following view controller illustrates the problem:

```Objective-C
#import "ViewController.h"
#import <MBProgressHUD/MBProgressHUD.h>

@implementation ViewController

- (void)viewDidAppear:(BOOL)animated
{
    [super viewDidAppear:animated];

    [self showHUD];

    dispatch_time_t delay = dispatch_time(DISPATCH_TIME_NOW, (int64_t)(3 * NSEC_PER_SEC));
    dispatch_after(delay, dispatch_get_main_queue(), ^{

        [self hideHUD];

        dispatch_async(dispatch_get_main_queue(), ^{

            // despite this call, HUD ends up being hidden!
            [self showHUD];

        });
    });
}

- (MBProgressHUD*)myHUD
{
    MBProgressHUD *hud = [MBProgressHUD HUDForView:self.view];
    if (hud == nil)
    {
        hud = [[MBProgressHUD alloc] initWithView:self.view];
        [self.view addSubview:hud];
    }
    return hud;
}

- (void)showHUD
{
    BOOL animated = YES;
    [[self myHUD] show:animated];
}

- (void)hideHUD
{
    [MBProgressHUD hideHUDForView:self.view animated:YES];
}

@end
```

**Comment by matej** [comment]
This might still be a problem with the latest version. Needs a test case and fix.

**Comment by matej** [comment]
f39a83a should make this a bit better
