### ISSUE TITLE
Getting rid of black background for the spinner

### ISSUE THREAD

**Issue by RyanKim01** [jdg/MBProgressHUD#297]
Hi
I am liking this library a lot but one thing. I wonder whether there is a way to get rid of black background on the spinner. I am using this library for my video player and whenever there is a video with white background, I see black spot due to black background of the spinner. 
Any advises will be appreciated!

**Comment by bablu-joshi** [comment]
in draw rect function 

add
     CGContextSetRGBFillColor(context, xxx/255, xxx/255, xxx/255, 0.8);

**Comment by matej** [comment]
The `bezelView` can now be directly accessed and customized.
