### ISSUE TITLE
Issue MBProgressHUD userInteractionEnabled

### ISSUE THREAD

**Issue by tenaz3** [jdg/MBProgressHUD#305]
This code below set user interaction true, but disable user touch events. It seems that do inverted work. Is this correct? 
The doc say: 
```swift
    var userInteractionEnabled: Bool // default is YES. if set to NO, user events (touch, keys) are ignored and removed from the event queue.
```
```swift
    func startLoading() {
           let loading = MBProgressHUD.showHUDAddedTo(self.view, animated: true)
           loading.mode = MBProgressHUDMode.Indeterminate
           loading.labelText = Strings.Loading
           loading.userInteractionEnabled = true
    }
```

**Comment by fmendoza** [comment]
I have the same doubt...

**Comment by matej** [comment]
Setting `userInteractionEnabled = true` means that the HUD receives touches. This in turn means that it prevents touches from passing through it to other views. Setting `userInteractionEnabled = failse` makes the hud opaque to touches, meaning that they pass through it to views that are positioned below it.
