### ISSUE TITLE
Carthage error: no shared framework schemes

### ISSUE THREAD

**Issue by jackyheart** [jdg/MBProgressHUD#307]
*** Skipped building MBProgressHUD due to the error:
Dependency "MBProgressHUD" has no shared framework schemes

Help...

**Comment by matej** [comment]
Should have been fixed a wile ago. https://github.com/jdg/MBProgressHUD/commit/019cae831440c15972048dd1653988ce2311405e @tomco might be able to help you. I don't use Carthage.

**Comment by tomco** [comment]
@jackyheart what did you define inside your `Carthage` file? The following works fine for me:

```
github "jdg/MBProgressHUD" "master"
```

**Comment by macdrevx** [comment]
What are the plans for the next tagged release that will include this change?

**Comment by matej** [comment]
I think this was resolved with 0.9.2. If not, a new release will come in about 2 weeks.
