### ISSUE TITLE
How to change UIActivityIndicatorView style?

### ISSUE THREAD

**Issue by Thavasidurai** [jdg/MBProgressHUD#313]
Thanks for this wonderful library!

I don't find any easy way to change the UIActivityIndicatorView style, it will be better if you add a property to change the UIActivityIndicatorView style.

Currently the default style has been set as UIActivityIndicatorViewStyleWhiteLarge.If anyone wants to change it into UIActivityIndicatorViewStyleWhite then they have to  modify it in MBProgressHUD.m so it would be really helpful if u include the property to change

**Comment by matej** [comment]
Just set your customized indicator as the `customView`.

**Comment by Thavasidurai** [comment]
@matej Thanks for your response!

Yes, we can set customized indicator as the customView but still it will be more easier if we add a property as like activityIndicatorColor

**Comment by matej** [comment]
`activityIndicatorColor` will be deprecated in the next version. Trying to keep the API compact. 
https://github.com/matej/MBProgressHUD/blob/v1/MBProgressHUD.h#L401

**Comment by Thavasidurai** [comment]
Cool! thanks for pointing this out I close this issue.
