### ISSUE TITLE
Please add a 0.9.2 tag for Carthage support

### ISSUE THREAD

**Issue by aral** [jdg/MBProgressHUD#322]
The shared framework is not in the 0.9.1 tag. Can you please add a tag (0.9.2) for the current master so that people can use it with Carthage by including, e.g., 

github "jdg/MBProgressHUD" ~> 0.9.2

Thanks! :)

(I’d submit a pull request but, afaik, tags don’t carry along and that’s literally the only change you need to make to support Carthage at the moment.) ;)

**Comment by matej** [comment]
Added. Could use an update to the README, if any Carthage users want to volunteer. 

Over the holidays I should be able to wrap up https://github.com/matej/MBProgressHUD/pull/68 and than we can make it `1.0.0`.

**Comment by aral** [comment]
Thanks + sure, I’ll prep a pull request for the readme now :)
