### ISSUE TITLE
Heads up: Swift version of the demo app

### ISSUE THREAD

**Issue by aral** [jdg/MBProgressHUD#325]
Hey Matej,

I’m using MBProgressHUD from Swift with a tiny Swift wrapper I call Progress Overlay (basically, a few additional methods and some syntactic sugar). See https://source.ind.ie/project/progress-overlay

I just ported the demo app to Swift, I thought you would want to know (should be trivial to add it to MBProgressHUD if you want to). Here’s a direct link to that: https://source.ind.ie/project/progress-overlay/blob/master/ProgressOverlayDemo/ProgressOverlayDemo/ViewController.swift

I might tackle a Swift rewrite at some point but it’s doing what I want it to for the time being and I should really get back to my main app.

I hope some of this is useful to you and thank you again for your excellent work on MBProgressHUD :)

**Comment by matej** [comment]
The demo app has been substantially modified in the latest version, so I'm closing this one for now. 

Created #332 to keep track of the whole Swift migration business. That's definitely something I'd love to see at some point. Together with dropping the legacy appearance and deprecated API.
