### ISSUE TITLE
Loader appears below the text

### ISSUE THREAD

**Issue by RonakPatel07** [jdg/MBProgressHUD#327]

**Comment by matej** [comment]
Looks above the text to me. The progress indicator partially covers some characters. In any case, I can't think of any reason why MBProgressHUD would not be positioned on the view that you put it on. You're responsible for adding it to the right view. Why do you think this is a MBProgressHUD bug?

**Comment by RonakPatel07** [comment]
sorry bro..
but i think in my code no any problem...
i closed my issue on github...happy ??
check this is my code...

- (void)webViewDidFinishLoad:(UIWebView *)webView {

    [MBProgressHUD hideAllHUDsForView:self.view animated:YES];

}

- (void)webViewDidStartLoad:(UIWebView *)webView {

    [MBProgressHUD showHUDAddedTo:self.view animated:YES];

}
