### ISSUE TITLE
HUD not dismissing when userInteractionEnabled set to NO and scroll view is scrolling

### ISSUE THREAD

**Issue by DmitrijMaz** [jdg/MBProgressHUD#328]
The reason behind this is that dismiss timer is added to NSRunLoop in default mode, which blocks the timer from firing if any of input sources is currently recognises events. To avoid this you need to add timer in NSRunLoopCommonMode.

```objective-c
self.minShowTimer = [NSTimer scheduledTimerWithTimeInterval:(self.minShowTime - interv) target:self 
								selector:@selector(handleMinShowTimer:) userInfo:nil repeats:NO];
```

scheduledTimerWithTimeInterval adds timer to NSDefaultRunLoopMode.

**Comment by matej** [comment]
Fixed in the latest master.
