### ISSUE TITLE
Multi line message

### ISSUE THREAD

**Issue by fulldecent** [jdg/MBProgressHUD#329]
The mode `MBProgressHUDModeText` only supports a single line of text. This is very limiting when the device may be a phone which is held vertical. This precludes me from using it to present arbitrary `NSError`s because they will usually not fit.

Here is the code I am using to present these errors:

        let hud = staticHud
        hud.mode = .CustomView
        hud.hide(false)
        hud.show(true)
        let view: UITextView = UITextView(frame: CGRectMake(0, 0, 200, 200))
        view.text = error.localizedDescription
        view.font = hud.labelFont
        view.textColor = UIColor.whiteColor()
        view.backgroundColor = UIColor.clearColor()
        view.sizeToFit()
        hud.customView = view

**Comment by matej** [comment]
This should now be possible with the exposed `label` and `detailsLabel`.
