### ISSUE TITLE
Hud isn't centered in TableView

### ISSUE THREAD

**Issue by Ferdy888** [jdg/MBProgressHUD#343]
See attached screenshot. When I am pressing the button with the red arrow, the hud gets shown. But it isn't centered. How to fix this?

Thank your for your answers.
![img_7146](https://cloud.githubusercontent.com/assets/16955036/12821059/1bcff9b0-cb62-11e5-8e39-aa92fc7cb639.PNG)

**Comment by matej** [comment]
Don't add the HUD directly onto a table view. A table view is a is a scroll view and all the content added to it will scroll. Add it to a superview or the window.
