### ISSUE TITLE
Carthage support removed?

### ISSUE THREAD

**Issue by danielphillips** [jdg/MBProgressHUD#344]
Hello, I think you guys added Carthage support a few months ago, I just ran `carthage update` and it wouldn't build MDProgressHUD. Are you aware of this?

```
*** Skipped building MBProgressHUD due to the error:
Dependency "MBProgressHUD" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/jdg/MBProgressHUD/issues/new
```

**Comment by matej** [comment]
Hm.. perhaps something went wrong wile merging the 1.0 branch. But the previous tags should not be affected. Never used cartage, so I can't help much. Perhaps @aral or @tomco can help. They worked on this.

**Comment by tomco** [comment]
Using `github "jdg/MBProgressHUD" "2107d0d6a32b508153c8b7fc57d33b661a595533"` (latest commit on master) works fine, also `github "jdg/MBProgressHUD" == 0.9.2`. Not sure what the problem is…

@danielphillips how did you define your dependency inside your `Cartfile`?

**Comment by danielphillips** [comment]
My Cartfile didn't specify a tag or branch. I've added that now after I saw some recent work in the repo.

```github "jdg/MBProgressHUD" "0.9.2"```
