### ISSUE TITLE
the MBProgressHUD downloaded from cocoapods is different from the MBProgressHUD downloaded from github?

### ISSUE THREAD

**Issue by crescentstar** [jdg/MBProgressHUD#345]
The version are also 0.9.2, but the content of the MBProgressHUD downloaded from cocoapods is different from the MBProgressHUD downloaded from github.

For example,

the content of the MBProgressHUD downloaded from github contains:

_@class MBBackgroundView;

but that code is not contained in MBProgressHUD downloaded from cocoapods.

Why?

**Comment by Fudge0952** [comment]
I can confirm this issue too

**Comment by matej** [comment]
Because the latest master does not necessary always represent the latest release. There has been ongoing work since the last cocoapods release. Checking out the [0.9.2 tag](https://github.com/jdg/MBProgressHUD/tree/0.9.2) will give you the same code as currently on cocoapods.
