### ISSUE TITLE
Can't install via Carthage

### ISSUE THREAD

**Issue by zetasq** [jdg/MBProgressHUD#346]
Carthage print this:
Dependency "MBProgressHUD" has no shared framework schemes.

Hope someone solve this :)

**Comment by matej** [comment]
Duplicate of https://github.com/jdg/MBProgressHUD/issues/344?

**Comment by zetasq** [comment]
Sorry, I didn't see that. #344 is closed but the problem still exists. Maybe it should get opened again? It seems the latest commit of this project doesn't have shared schemes.

**Comment by matej** [comment]
![screen shot 2016-02-12 at 08 09 09](https://cloud.githubusercontent.com/assets/91322/13000852/f020da6a-d15f-11e5-83d9-013d1ba84598.png)

Looks fine to me. But feel free to open a PR if you know what's up.

**Comment by zetasq** [comment]
Maybe this is a bug from Carthage? Really weird.
