### ISSUE TITLE
Add support for NSProgress

### ISSUE THREAD

**Issue by VilemKurz** [jdg/MBProgressHUD#347]
It would be great if one could just feed MBProgressHUD with activated NSProgress instance, so that it updates progress automatically.

**Comment by brendand** [comment]
+1 For this feature. I would love this. Right now I have to add an observer on the NSProgress and update the MBProgressHUD myself.

**Comment by chinnuios** [comment]
@VilemKurz  @brendand  Hi I am working on chatting app. Though i using  MBProgressHUDModeAnnularDeterminate Loader using podfile. Working fine. that method I am using in Tableview Cell for image loading, but when i scroll and uploading new image from iphone to server then  it is showing loader  on every image cell . How to resolve it ?? Please Help me.

**Comment by matej** [comment]
@chinnuios This is completely off topic and a re-post of https://github.com/jdg/MBProgressHUD/issues/367. Don't do that.
