### ISSUE TITLE
when use graceTime property,it seems not working

### ISSUE THREAD

**Issue by swsdyg** [jdg/MBProgressHUD#350]
when i use graceTime,the hud does not show forever,is  there some wrong with the  handleGraceTimer: 

- (void)handleGraceTimer:(NSTimer *)theTimer {
    // Show the HUD only if the task is still running
    if (self.hasFinished) {
        [self showUsingAnimation:self.useAnimation];
    }
}

**Comment by matej** [comment]
Does this fix your issue? https://github.com/jdg/MBProgressHUD/pull/349

**Comment by swsdyg** [comment]
I change the code '(self.hasFinished) ' to (!(self.hasFinished) )，and it is ok.
Did I use this property in the wrong way?
The follow is my code 
       MBProgressHUD *hud = [[MBProgressHUD alloc] initWithView:self.navigationController.view];
	[self.view addSubview:hud];
	hud.graceTime = .5f;
	[hud showAnimated:YES];
