### ISSUE TITLE
Update cocoapods

### ISSUE THREAD

**Issue by marekzehra** [jdg/MBProgressHUD#351]
Please release current (customizable white) version as new version in cocoapods

**Comment by filipmelik** [comment]
+1
When installed from CocoaPods, it installs the version from **legacy** branch.
As a temporary workaround, I have added this to my podfile:
`pod 'MBProgressHUD', :git => 'https://github.com/jdg/MBProgressHUD.git', :tag => "master"`

**Comment by matej** [comment]
1.0 isn't ready yet. If you still want the latest you can always do what @filipmelik suggested.
