### ISSUE TITLE
Circular bezelView

### ISSUE THREAD

**Issue by brendand** [jdg/MBProgressHUD#354]
In the legacy version I was able to use the following code to get a nice circular shaped view with the activity spinner inside. The bezelView was slightly larger than the UIActivityIndicator itself.

```
- (void)startLoading {
	self.hud = [[MBProgressHUD alloc] initWithView:self.iconImageView];
	[self.iconImageView addSubview:self.hud];
	self.hud.color = [UIColor colorWithRed:0.0471 green:0.349 blue:0.6 alpha:1.0];
	self.hud.yOffset = 3.5;
	self.hud.cornerRadius = 22.0;
	self.hud.margin = 4.0;
	[self.hud show:YES];
}
```

But nothing I do now with the latest version seems to make that work anymore. It's always much too big and never a perfect circle like I had it before.

Is there any other way to control the shape and size of the bezelView?

**Comment by matej** [comment]
Works just fine here. Even with the deprecated API you are using. I just need to set a different radius. 

![screen shot 2016-04-02 at 21 10 37](https://cloud.githubusercontent.com/assets/91322/14228544/970121e4-f917-11e5-9a4e-63476cf1f221.png)

![simulator screen shot 2 apr 2016 21 11 16](https://cloud.githubusercontent.com/assets/91322/14228546/9b6eeca2-f917-11e5-89db-ab48613b159b.png)

To make this a bit more robust, and less magic number fiddling, rather subclass `MBPorgessHUD`, override `layoutSubviews` and after calling super do something like this: `self.bezelView.layer.cornerRadius = CGRectGetHeight(self.bezelView.frame) / 2.f;`.
