### ISSUE TITLE
Missing button property

### ISSUE THREAD

**Issue by jakubprusa** [jdg/MBProgressHUD#355]
Hi,

I seen in your example this piece of code

`MBProgressHUD *hud = [MBProgressHUD showHUDAddedTo:self.navigationController.view animated:YES];

    // Set the determinate mode to show task progress.
    hud.mode = MBProgressHUDModeDeterminate;
    hud.label.text = NSLocalizedString(@"Loading...", @"HUD loading title");

    // Configure the button.
    [hud.button setTitle:NSLocalizedString(@"Cancel", @"HUD cancel button title") forState:UIControlStateNormal];
    [hud.button addTarget:self action:@selector(cancelWork:) forControlEvents:UIControlEventTouchUpInside];`

I tried to in my own project when MBProgressHUD is added through cocoapods but no button property is visible but version in example and pod seems to be same.

Can you help me what's wrong? 

Regards,
Jakub P.

**Comment by matej** [comment]
This feature has not yet been made available via cocoapods.

**Comment by jakubprusa** [comment]
Ok, but what is confusing is that version in comments in the beginning of file is same in example and cocoapods. Maybe different version number in file will make this more clearer. :)
