### ISSUE TITLE
iOS 6 compatibility

### ISSUE THREAD

**Issue by maxgorodivskyi** [jdg/MBProgressHUD#360]
I have to make app backward compatible and encountered this issue with HUD label.
No custom fonts or label styling was used.
![img_0153](https://cloud.githubusercontent.com/assets/18209424/14203057/5e24c664-f804-11e5-8958-bf0fcf43f080.jpg)
iOS version 6.1.3

 I tried using legacy branch and everything works as expected.
![img_0155](https://cloud.githubusercontent.com/assets/18209424/14203165/f148055a-f804-11e5-8b03-dcb457833ed1.jpg)

**Comment by jasonz1987** [comment]
+1 i've met the same issue..

**Comment by matej** [comment]
I unfortunately no longer have any iOS 6 devices. If you figure out what's wrong please issue a pull request. Might be just an incorrectly set (default) background color?

**Comment by yas375** [comment]
According to [Mixpanel trends](https://mixpanel.com/trends/#report/ios_frag) only 0.26% are using iOS 6. 
@maxgorodivskyi I would suggest to use it a reasoning to stop supporting iOS6. It will definitely much more pleasant for you, as developer, to work with newer api. Good luck!

![2016-04-15_1850](https://cloud.githubusercontent.com/assets/217368/14578346/fa7fb384-033a-11e6-8d95-951181806183.png)

**Comment by matej** [comment]
I'm shooting in the dark here but abf99ff might fix this. Would appreciate it, if any of you old-school boys could confirm this for me.
