### ISSUE TITLE
Every time Loading In TableView Cell 

### ISSUE THREAD

**Issue by chinnuios** [jdg/MBProgressHUD#367]
Hi I am working in that  MBProgressHUDModeAnnularDeterminate Loader using podfile. Working fine. I am using in Tableview Cell for image loading, but when i scroll then every time it is showing loader and tableview not moving smoothly.  How to resolve it ?? Please Help me.

**Comment by matej** [comment]
Depending on where you put the HUD, you might need to set `hud.userInteractionEnabled = NO`. Other than that, that is more likely an issue with your image loading than `MBProgressHUD`.

**Comment by chinnuios** [comment]
@matej  Thanks for the replay I am working with the Chatting so when i send image ineed to do animation like same as Whatsapp. so i use BProgressHUD.it is working fine. my code in like below

 
        MBProgressHUD *hud = [MBProgressHUD showHUDAddedTo:self.imageview animated:YES];
        
        // Set the annular determinate mode to show task progress.
        hud.mode = MBProgressHUDModeAnnularDeterminate;
        hud.label.text = NSLocalizedString(@"Loading...", @"HUD loading title");
        
        dispatch_async(dispatch_get_global_queue(QOS_CLASS_USER_INITIATED, 0), ^{
            // Do something useful in the background and update the HUD periodically.
            [self doSomeWorkWithProgress];
            dispatch_async(dispatch_get_main_queue(), ^{
                [hud hideAnimated:YES];
            });
        });
but every time it is loading at every indexpath so how to achieve this please help me

**Comment by matej** [comment]
I have trouble understanding you and don't know what you're asking. Also, this is an issue tracker from MBProgressHUD and not a support forum. I suggest you ask on http://stackoverflow.com.
