### ISSUE TITLE
Can Hud have a timeout property to let it hide

### ISSUE THREAD

**Issue by aozhimin** [jdg/MBProgressHUD#369]
can MBProgressHUD have a timeout property, if the time is gone, it will dismiss it self, cause in my app, some times I show a hud in loading style, but in some case the hud dismiss not called, user can not do anything in current page!

**Comment by yas375** [comment]
You can call [`hideAnimated:afterDelay:`](https://github.com/jdg/MBProgressHUD/blob/5c3b93fe4ff9542e08e6b3a98d945805131eb55c/MBProgressHUD.h#L162-L172) after presenting your HUD.

**Comment by aozhimin** [comment]
yep, I konw this api, but i don't want the dismiss at the specified time, for example, every time before I make a network request I show a hud, when the network callback call, I dismiss hud, For some reason not to know, the network callback not be called, then hud not dismiss, it will still show that.

**Comment by aozhimin** [comment]
@yas375

**Comment by yas375** [comment]
You should solve the problem in your network layer. Maybe network request fails and you don't handle it? Debug and find the root problem why your completion block is not called. Don't try to mask the problem.

In any case, it's not the MBProgressHUD's issue or a reasonable feature request IMO.

**Comment by aozhimin** [comment]
Got it, thank you for answer me!
