### ISSUE TITLE
Cannot get lastest version of MB

### ISSUE THREAD

**Issue by Hogantry** [jdg/MBProgressHUD#370]
I user cocoapods of Version 1.0.0.beta.8, but cannot get lastest version of MB. When i check the MB.h which i get, it's different from the github's.

**Comment by yas375** [comment]
@Hogantry while there is no recent official release, you can just point to any commit you want in your Podfile.

```ruby
pod 'MBProgressHUD', :git => 'https://github.com/carezone/MBProgressHUD.git', :commit => '5c3b93f'
```

**Comment by Hogantry** [comment]
Thank you very much, have a nice day.

**Comment by yas375** [comment]
You are very welcome :)
