### ISSUE TITLE
Crash when using MBRoundProgressView in a UITableViewCell

### ISSUE THREAD

**Issue by Dean151** [jdg/MBProgressHUD#371]
Hi !
I'm using MBProgressHUD in my app, and I wanted to use the MBRoundProgressView in cells to make the same effect than in the Music App when downloading a track.

But sometime, I experience a Crash that I am not quite sure to understand :

```
*** Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <MBRoundProgressView 0x18af4120> for the key path "progressTintColor" from <MBRoundProgressView 0x18af4120> because it is not registered as an observer.'
```

Any leads to fix it somehow ?

Let add that I use Notification Center to send progressions to the right cell

**Comment by matej** [comment]
Should no longer happen with the latest master as KVO is no longer used.
