### ISSUE TITLE
i want  translucent  bezeView,but  the label translucent

### ISSUE THREAD

**Issue by fanxiangyang** [jdg/MBProgressHUD#376]

**Comment by matej** [comment]
Huh? ¯\_(ツ)_/¯

**Comment by fanxiangyang** [comment]
1.my code  
MBProgressHUD *hud = [MBProgressHUD showHUDAddedTo:[[UIApplication sharedApplication].windows objectAtIndex:0] animated:YES];
    hud.mode = MBProgressHUDModeCustomView;
    hud.userInteractionEnabled = NO;
    //i want backgroundView : black=0.5alpha
    hud.backgroundView.backgroundColor=[UIColor colorWithWhite:0.0 alpha:0.5];    
    hud.contentColor=[UIColor whiteColor];
    //but the bezelView.backgroundColor=0.5alpha  i want 1.0alpha
    hud.bezelView.backgroundColor=[UIColor colorWithRed:0 green:0 blue:0 alpha:1];
    hud.detailsLabel.text = @"hello ";
    hud.removeFromSuperViewOnHide = YES;
    [hud hideAnimated:YES afterDelay:2];
2. //i want hud.backgroundView.backgroundColor : black=0.5alpha
    //but the bezelView.backgroundColor=0.5alpha  i want 1.0alpha

**Comment by matej** [comment]
Set `MBProgressHUDBackgroundStyleSolidColor` on the bezel if you want a solid opaque color.

**Comment by fanxiangyang** [comment]
thank you!  it good
