### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by chinnuios** [jdg/MBProgressHUD#378]
Hi , I am Working on chatting App. The library is easy to use and lightweight in terms of understanding it, but there seems to be a problem. If I call showHUDAddedTo in a url image, am calling an image  from iphone to server (eg: in phone i click attachment button taped and select image send to other), it is added and everything is ok, but if  hud shows again all image, when i would send image to other. I am using somessaging third party. please help me.. how to show progress as like whatsapp (send and receive image type).

**Comment by matej** [comment]
I have trouble understanding you. This is also not a support forum, but a bug tracker. For general support you can try http://stackoverflow.com.
