### ISSUE TITLE
how to change the background color

### ISSUE THREAD

**Issue by abhi2412shek** [jdg/MBProgressHUD#381]

**Comment by yas375** [comment]
Probably would be more appropriate to ask such questions at StackOverflow and to open an issue when you are reporting an issue. issue != help request

See https://github.com/jdg/MBProgressHUD/blob/f3732cc1058da7d9e9856a27c5e476f34fb28673/MBProgressHUD.h#L267
and https://github.com/jdg/MBProgressHUD/blob/f3732cc1058da7d9e9856a27c5e476f34fb28673/MBProgressHUD.h#L368-L383

```swift
hud.backgroundView.color = UIColor.orangeColor()
```

**Comment by markltownsend** [comment]
Not technically a bug, but would be nice to be able to set the background color for all MBProgressHUDs rather than setting it for each instance created at creation time.  For instance, implement the UIAppearance Protocol.
