### ISSUE TITLE
Why not keep the completionBlock?

### ISSUE THREAD

**Issue by hulizhen** [jdg/MBProgressHUD#384]
Hi.

In the latest version, it seems that you guys are considering to remove the completionBlock and replace it with the MBProgressHUDDelegate instead?

In my/some case, the completionBlock is a much more elegant approach to **reduce code separation and global variables** in comparison to the MBProgressHUDDelegate which kinda messing up my code.

How about keeping both completionBlock and MBProgressHUDDelegate?

**Comment by matej** [comment]
The reason for removing it was mainly that it was mainly meant for the GCD helper that got deprecated. But fair enough. I brought it back in 383e8f51310d803838b49f22fea9e4e316f1339c.

**Comment by hulizhen** [comment]
Great! Thanks :)
