### ISSUE TITLE
Please push version tags to Github

### ISSUE THREAD

**Issue by paulfurley** [jdg/MBProgressHUD#385]
I just spent quite a bit of time using version `0.41` as this was the latest tag I could see in Github. It's quite misleading to have out of date tags - would be great if you could tag new releases when they're made.

Cheers!

**Comment by matej** [comment]
I'm not sure what you are talking about. 

<img width="330" alt="screen shot 2016-06-02 at 14 00 44" src="https://cloud.githubusercontent.com/assets/91322/15744130/7596765c-28ca-11e6-89f6-94c59e772a74.png">

**Comment by paulfurley** [comment]
@matej Hmm. Apparently we're having a bad day... Apologies and thanks!
