### ISSUE TITLE
Podspec file does not specify deployment version 

### ISSUE THREAD

**Issue by Voley** [jdg/MBProgressHUD#389]
MBProgressHUD has few checks for deployment version in its code.

At this moment podspec in Cocoapods repository https://github.com/CocoaPods/Specs/blob/master/Specs/MBProgressHUD/0.9.2/MBProgressHUD.podspec.json does not specify deployment version.

So when you install MBProgressHUD with Cocoapods 1.0+ it sets MBProgressHUD deployment target to 4.3 and breaks core functionality.

Without it some functionality breaks, for example changing activity indicator color.

To fix this the podspec in project https://github.com/jdg/MBProgressHUD/blob/master/MBProgressHUD.podspec should be uploaded to cocoapods repository, because it is not.

**Comment by matej** [comment]
Will be done as part of #334.
