### ISSUE TITLE
Should MBProgressHUD support to customize `line width` for annular progress view?

### ISSUE THREAD

**Issue by xohozu** [jdg/MBProgressHUD#392]
I have to say that **MBProgressHUD** provides the full customized access for users, except for the `line width` of annular progress view. The value of `line width` is specific which assigned with 2.0(for iOS7 later) or 5.0 as the following code . Is there a reason for this ?
```objective-c
CGFloat lineWidth = isPreiOS7 ? 5.f : 2.f;
```
Although I can reach my goal by hacking, I think it could be supported by official repo.

**Comment by matej** [comment]
iOS 7 has a slimmer design then the old iOS 6 appearance. Just to match the OS design a bit better.

**Comment by matej** [comment]
As of whether to expose that as API. I really see this as an edge case. This is the first time someone requested it although the functionality has been there for ages. Ideally I would want to keep the API footprint as small as possible. I would recommend that you just fork the repository and customize it for yourself.

**Comment by xohozu** [comment]
Thanks for your explanation.👍
