### ISSUE TITLE
Support for tvOS (Apple TV)

### ISSUE THREAD

**Issue by carlosandresSanchez** [jdg/MBProgressHUD#395]

**Comment by yas375** [comment]
It seems to be supported already: https://github.com/jdg/MBProgressHUD/blob/59a8240da67a8c98ac7e77da2fa198d21b1ab03c/MBProgressHUD.podspec#L16 (#357). Or have you found issues with it?

**Comment by matej** [comment]
There is even a small demo app in 1.0. If you find any issues, please open additional tickets.
