### ISSUE TITLE
App crashes after version 1.0 update

### ISSUE THREAD

**Issue by SlavcoPetkovski** [jdg/MBProgressHUD#396]
In older version I was showing MBProgressHUD like this:
`let loadingNotification = MBProgressHUD.showHUDAddedTo(self.view, animated: true)
        loadingNotification.mode = MBProgressHUDMode.Indeterminate
        loadingNotification.label.text = "Loading"`

After upgrading to version 1.0 I got crash like:
`[MBProgressHUD hideAnimated:]: unrecognized selector sent to instance` and same for `loadingNotification.label`

**Comment by matej** [comment]
How can I reproduce it? Is this reproducible in the demo app?

**Comment by SlavcoPetkovski** [comment]
Just add `let loadingNotification = MBProgressHUD.showHUDAddedTo(self.view, animated: true)
        loadingNotification.mode = MBProgressHUDMode.Indeterminate
        loadingNotification.labelText = "Loading"`, but I'm not placing this code on main thread, maybe thats the issue. Should I place it in GCD's main queue?

**Comment by SlavcoPetkovski** [comment]
It crashes no more. Close the issue. I've just put the hiding process in main queue.

**Comment by matej** [comment]
You probably hit one of the new main thread assertions then. That needs to be called on the main thread. This was always a requirement - it's just being explicitly enforced now.
