### ISSUE TITLE
Spinner is not in the center on 1.0.0

### ISSUE THREAD

**Issue by GabeJacobs** [jdg/MBProgressHUD#398]
Hey!

Love the new update, but it looks like there is an issue with centering the spinner on 1.0.0

Here is a blown up image. You'll notice the spinner is a tiny bit too high and too far left. Would love a fix! Thanks.
- Gabe

![screen shot 2016-07-19 at 3 11 23 pm](https://cloud.githubusercontent.com/assets/953195/16963338/f8ba454a-4dc3-11e6-9098-6519a3c59fd4.png)

**Comment by PiaoL** [comment]
![image](https://cloud.githubusercontent.com/assets/15139973/19877686/5d9bad1e-a01c-11e6-81b0-0434898719b6.png)

**Comment by PiaoL** [comment]
![image](https://cloud.githubusercontent.com/assets/15139973/19877744/d0af4be4-a01c-11e6-93c1-b8233f4bbb51.png)

**Comment by RojS** [comment]
This appears to be a bug in UIActivityIndicatorView. 
If line 460 in MBProgressHUD.m is commented out the spinner remains centred. 

![5](https://cloud.githubusercontent.com/assets/25417839/23813305/644405f6-05ef-11e7-9e89-0fd14e5bfe93.png)


This bug can be reproduced independently of MBProgressHUD. 
It is strange behaviour. 
It appears that if UIActivityIndicatorView.color is set to anything other than opaque white in the kCGColorSpaceDeviceGray color space then the spinner is offset. 

![b](https://cloud.githubusercontent.com/assets/25417839/23813362/9c1e6b92-05ef-11e7-91dc-0c94d033d5f9.png)

![a](https://cloud.githubusercontent.com/assets/25417839/23813375/a8804694-05ef-11e7-9d05-0bf5535c4137.png)

**Comment by RojS** [comment]
By the way I really prefer MBProgressHUD over SVProgressHUD but would love to see an "annular indeterminate" option for the activity indicator. Perhaps this might be the catalyst for it ;-) 

![screen shot 2017-03-11 at 12 51 50 am](https://cloud.githubusercontent.com/assets/25417839/23814670/74e27202-05f5-11e7-844e-f6291ab40d90.png)

**Comment by matej** [comment]
Yeah, I could confirm that this is a bug on `UIActivityIndicatorView`. If anybody wants to file a radar, that'd be great.

**Comment by RojS** [comment]
I logged a bug in Apple Bug Reporter (the black hole) on 11-Mar-2017 (#30980078) with detailed information. But I have never received a response, it was not even marked as a duplicate, and is still open.
