### ISSUE TITLE
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'MBProgressHUD needs to be accessed on the main thread.

### ISSUE THREAD

**Issue by CoderTaoX** [jdg/MBProgressHUD#399]
My app Login error , hide the hud , more than three times show that cache.

**Comment by matej** [comment]
Read the message. Make sure you call MBProgressHUD methods on the main thread.

**Comment by Anbu312** [comment]
Yes, I call MBProgressHUD method on the main thread. I am facing the same issue.
