### ISSUE TITLE
Change blur background color

### ISSUE THREAD

**Issue by carlosandresSanchez** [jdg/MBProgressHUD#401]
I upgrade to the version 1.0.0.

How can i change the background color when i use 
`[MBProgressHUD showHUDAddedTo:view animated:YES] `?

I tried this, but nothing happens : 

```
MBProgressHUD * mbProgressHUD = [MBProgressHUD showHUDAddedTo:view animated:YES];
mbProgressHUD.backgroundView.color = [UIColor blackColor];
mbProgressHUD.backgroundView.style = MBProgressHUDBackgroundStyleSolidColor;
```

**Comment by MeGaPk** [comment]
+1

**Comment by MeGaPk** [comment]
Solution:
need use just:
```
[mbProgressHUD.bezelView setBackgroundColor:[UIColor darkGrayColor]];
```

**Comment by charliebartel** [comment]
@carlosandresSanchez This works for me:

`	[hud.bezelView setBackgroundColor:[UIColor blackColor]];
	hud.contentColor = [UIColor whiteColor];`

**Comment by ed8009** [comment]
But how to remove the background?
I tried this, but nothing happens :

```
[hud.bezelView setBackgroundColor:[UIColor clearColor]];
hud.contentColor = [UIColor clearColor];
```

**Comment by MeGaPk** [comment]
@ed8009 
maybe: 
```
[hud.bezelView setBackgroundColor:[UIColor clearColor]];
hud.bezelView.contentColor = [UIColor clearColor];
``` 
?

**Comment by ed8009** [comment]
@MeGaPk 
Is it possible?
`hud.bezelView.contentColor`

**Comment by ed8009** [comment]
It seems that it works:   
 ```
[progressHud.bezelView setBackgroundColor:[UIColor clearColor]];
    progressHud.bezelView.color = [UIColor clearColor];
    progressHud.bezelView.style = MBProgressHUDBackgroundStyleSolidColor;
```

**Comment by carlosandresSanchez** [comment]
Well, with all the comments, I found the following:

- Changes `"contentColor"` if you want to change the spinner's color

- Change` "bezelView.color"` if you wan to change the background color of the hub. You need to set `"bezelView.style"` as `MBProgressHUDBackgroundStyleSolidColor` to remove the blur effect.

Thanks for your help!!
