### ISSUE TITLE
Add Alpha for Background View

### ISSUE THREAD

**Issue by theory** [jdg/MBProgressHUD#405]
I'm using the solid color background, but would like to set its alpha level. Currently I can only do that if I call it after calling a show method. Maybe it'd make sense to add an `alpha` property to MBBackgroundView that defaults to `1.0f` and set that value when presenting the HUD?

**Comment by gauravkeshre** [comment]
You can use `UIColor` with alpha
`[UIColor colorWithRed:1.0 green:0.0 blue:0.0 alpha:0.5];
`

**Comment by theory** [comment]
Oh, of course, that's even better. I should have thought of that. Thank you!
