### ISSUE TITLE
Provide a MBProgressHUDBackgroundStyle that allows access to Parent View

### ISSUE THREAD

**Issue by gauravkeshre** [jdg/MBProgressHUD#406]
It will a good to have feature when I can still interact with the parent view while the loader is showing.

Thanks

**Comment by gauravkeshre** [comment]
For time being I have added this feature in my own fork
[here](https://github.com/gauravkeshre/MBProgressHUD.git)
branch : **interactableSuperView**

usage with cocoa pods

`pod 'MBProgressHUD', :git => 'https://github.com/gauravkeshre/MBProgressHUD.git', :branch => 'interactableSuperView'
`

**Comment by matej** [comment]
You just need to set `hud.userInteractionEnabled = NO`.
