### ISSUE TITLE
Using HUD in iphone4 and IOS7 was not work

### ISSUE THREAD

**Issue by yoriWang** [jdg/MBProgressHUD#410]
Hi,I was used the class in my project, but there's a mistake when i was running my iphone4 and the systemVersion is 7.1.
@jdg 
the crash happened here

`dispatch_async(dispatch_get_global_queue(QOS_CLASS_USER_INITIATED, 0), ^{

```
    // Do something useful in the background
    [self doSomeWork];

    // IMPORTANT - Dispatch back to the main thread. Always access UI
    // classes (including MBProgressHUD) on the main thread.
    dispatch_async(dispatch_get_main_queue(), ^{
        [hud hideAnimated:YES];
    });
});`
```

please give me some suggestions,Thanks.

**Comment by matej** [comment]
Was this in the demo project? What kind of crash did you get? Please provide move details.

**Comment by yoriWang** [comment]
Demo in my repositories，just one project-LoginAndRegist. Please open LoginViewController.m and RegisterViewController.m, there are "#warning ...". Thank you.

**Comment by matej** [comment]
I don't have an iOS 7.1 device around, so I can't debug this for you. If you can provide the exact crash stack trace / exception message / whatever I might be able to help a bit, but that's just about all I can do.

**Comment by yoriWang** [comment]
I'm so sorry, I can't get the exception message, when i want the application crash and get some exception message, but exception pause here in this code: 
`dispatch_async(dispatch_get_global_queue(QOS_CLASS_USER_INITIATED, 0), ^{`
I just get the prompt in here, "Thread 1:EXC_BAD_ACCESS(code=1, address=0x30)".
`libdyld.dylib`start:
    0x3aa9eab4 <+0>: nop    
->  0x3aa9eab6 <+2>: blx    0x3aa9eaf8                ; symbol stub for: vproc_swap_integer
    0x3aa9eaba <+6>: trap`
this is Thread 1 -> 19 start.

My English is so poor, so I can't provide many descriptions.

**Comment by matej** [comment]
This doesn't look like a MBProgressHUD related issue.

**Comment by yoriWang** [comment]
but the MBProgressHUD demo running in the same issue occurred on the iPhone4



发自我的小米手机
在 Matej Bukovinski <notifications@github.com>，2016年8月17日 21:48写道：

This doesn't look like a MBProgressHUD related issue.

**Comment by sacot41** [comment]
I have the same problem; app crash on [hud hideAnimated:YES] on iphone 4s with iOS 7.1.2. I going to check this today, because my app is in production......

**Comment by sacot41** [comment]
Ok, I'm stupid....

The error was :

> Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[MBProgressHUD hideAnimated:]: unrecognized selector sent to instance 0x15587ef0'


And the code : 

`
MBProgressHUD *hud = [MBProgressHUD showHUDAddedTo:self.window animated:YES];
hud.detailsLabelText=NSLocalizedString(@"Loading...", nil);
 [sNetworkCenter syncDataBase:^(bool success) {
        [hud hideAnimated:YES];
}];`

I have to replace " [hud hideAnimated:YES];" with "[MBProgressHUD hideHUDForView:self.window animated:YES];" and everything work good.

**Comment by matej** [comment]
Version 1.1 drops iOS 7.0 support, so closing this.
