### ISSUE TITLE
HUD Center position error

### ISSUE THREAD

**Issue by chronos92** [jdg/MBProgressHUD#413]
After updating to version 1.0 the methods showAnimated: and show: show de view on top left angle instead in center of view.

I have to manually set the center with code :
`hud.center = view.center`

![simulator-screen-shot-17-ago-2016 -08 51 57](https://cloud.githubusercontent.com/assets/1763963/17727232/3d258168-6458-11e6-9696-fe73d930fa61.png)

**Comment by matej** [comment]
Can you provide a way to reproduce this?

**Comment by chronos92** [comment]
Sorry for the report but now i do not have anymore the problem. sorry again
