### ISSUE TITLE
Can not set bezelView appearance

### ISSUE THREAD

**Issue by Whirlwind** [jdg/MBProgressHUD#416]
I can set the appearance by below code:

```
    MBProgressHUD *hud = [MBProgressHUD appearance];
    hud.contentColor = [UIColor whiteColor];
```

But I not found the way to set appearance backgroundColor of the bezelView.

**Comment by qtds8810** [comment]
you should set the hud's mode, then set:
        hud.bezelView.color = kColor_Black
        hud.bezelView.alpha = 0.8
that's all

**Comment by Whirlwind** [comment]
I known. But I hope use the `appearance` to set global color of bezelView.

**Comment by Dev-Khaled** [comment]
Objective-C
`    [[MBBackgroundView appearance] setColor:UIColor.blueColor];
`

Swift

`    MBBackgroundView.appearance().color = UIColor.blue;
`
