### ISSUE TITLE
-MBProgressMaxOffset moves the hud under the navigation bar

### ISSUE THREAD

**Issue by dhiraj** [jdg/MBProgressHUD#417]
I want to have the Progress HUD attached to the the top left corner of my view controller. When I set the offset to `CGPointMake(-MBProgressMaxOffset, -MBProgressMaxOffset)` it does move to the top left, but it moves _all_ the way up, under the navigation bar, ideally it should stay below the navigation bar.

Any ideas on how one could go about doing this?

**Comment by matej** [comment]
Those values are pretty primitive and more of workaround then proper positioning. One way you could approach this to use a wrapper view that you position as you want and then add MBProgressHUD to it.
