### ISSUE TITLE
hi~I got a problem with it,when I use MBProgressHUD for its customView

### ISSUE THREAD

**Issue by xiaoxiongke** [jdg/MBProgressHUD#421]
the customView 's frame  always go wrong. manual set frame didn't work? please help me how to custom a cunstomView with MBProgressHUD.
![qq20160906-0](https://cloud.githubusercontent.com/assets/11352346/18334695/00157a48-75ac-11e6-83e3-59993da9decd.png)

**Comment by matej** [comment]
This looks like your custom view might be missing to declare `intrinsicContentSize`.
