### ISSUE TITLE
hi  Questions about minSize

### ISSUE THREAD

**Issue by woshigaokeji** [jdg/MBProgressHUD#422]
// Set the annular determinate mode to show task progress.
    hud.mode = MBProgressHUDModeText;
    hud.label.text = NSLocalizedString(@"Message here!", @"HUD message title");
    // Move to bottm center.
    hud.offset = CGPointMake(0.f, MBProgressMaxOffset);
    // Will look best, if we set a minimum size.
    hud.minSize = CGSizeMake(50.f, 50.f);

why？I set the size of the minsize But the size of the display does not change Don't the size of the hud can change?Or has a default minimum can not be set smaller

**Comment by matej** [comment]
Not sure if I understand the question. The HUD will fit is size to the content you set. If the `minSize` is smaller then the fitting size then the fitting size is used.
