### ISSUE TITLE
customView

### ISSUE THREAD

**Issue by XiaoJuanW** [jdg/MBProgressHUD#424]
Hi, I have a issue. Is that the mode customView can only be imageView? I define my own view, it dosn't show ...

**Comment by xiaoxiongke** [comment]
It seems any customView wouldn't show in right frame...

**Comment by XiaoJuanW** [comment]
sorry， what's the meaning of 'in right frame' ?

**Comment by xiaoxiongke** [comment]
#421 
when the frame set or changed,the customView wouldn't change.

**Comment by qingqinghebiancao** [comment]
1. Check if you have set the hud mode to MBProgressHUDModeCustomView. 
2. See #432 .

**Comment by aryaxt** [comment]
This broke on 1.0. prior to that customView was working for me

**Comment by aryaxt** [comment]
It looks like `indicator.translatesAutoresizingMaskIntoConstraints = NO;` is causing the issue

**Comment by matej** [comment]
You need to make sure `intrinsicContentSize` is implemented and returning an appropriate size since 1.0. It's needed for AutoLayout to correctly position the custom view.
