### ISSUE TITLE
Why MBProgressHUD cannot show in the middle of my screen?

### ISSUE THREAD

**Issue by kevinlee85** [jdg/MBProgressHUD#425]
Hi :
I have one tableView in my UIViewController. When i scrolled down some items(more than one page), then fire MBProgressHUD to show up. I think MBProgressHUD maybe show up at the very beginning of the screen, but not the middle of the visible part. Do you know how to fix it?

**Comment by ZhaoheMHz** [comment]
just add the hud to self.view?  you can have a try

**Comment by matej** [comment]
https://github.com/jdg/MBProgressHUD/issues/343
