### ISSUE TITLE
initWithView , also add HUD(self) as subview to the passed view?

### ISSUE THREAD

**Issue by bhargavms** [jdg/MBProgressHUD#427]
In initWithView , also add HUD(self) as subview to the passed view? Not just initWithBounds? I can give a PR for this if you think its not a wrong thing to do.

**Comment by matej** [comment]
Thanks for the suggestions, but that should not be the initializers responsibility.

**Comment by bhargavms** [comment]
Ok how about a static class method initializer, that just initializes the HUD object to the view bounds and attaches the HUD object to view, but doesnt call showAnimated:

**Comment by matej** [comment]
Feel free to define a category for yourself if you want that. I would like to keep the API as small as possible and there are already static helpers for that. Although they do call `showAnimated:` as you pointed out.
