### ISSUE TITLE
Adding this to navigation bar

### ISSUE THREAD

**Issue by eighteight** [jdg/MBProgressHUD#430]
Hi,

Is there a way to add this to a navigation bar button item?

Something like this:

`myUiViewController.navigationItem.leftBarButtonItem = [[UIBarButtonItem alloc] initWithCustomView:SOMEVIEW];`

Thanks.

**Comment by matej** [comment]
I never tried and it certainly wasn't designed for that. If nothing else, it probably won't fit / look good. But you can try if you like. :)
