### ISSUE TITLE
Swift 3 Deprecated warnings

### ISSUE THREAD

**Issue by AnthonyMDev** [jdg/MBProgressHUD#431]
When using this library from a Swift 3 target, I'm getting warnings for deprecated methods on `show(animated:)` and `hide(animated:)`.

`'show' is deprecated. Use showAnimated: instead.`
`'hide' is deprecated. Use hideAnimated: instead.`

This is because Swift 3 converts the syntax for the Objective-C method `showAnimated:` and `hideAnimated:` to `show(animated:)` and `hide(animated:)` respectively.

In Swift 3, the deprecated method syntax is exactly the same as the new method's syntax. I'm hoping we can get a version where the deprecated methods are removed, or something is changed to remove these warnings soon. Having a bunch of warnings in my project is driving me crazy! 

Thanks

**Comment by matej** [comment]
Looks like the best option here is to get rid of the deprecations. People should have had enough time to upgrade by now.

**Comment by matej** [comment]
Should be fixed since 643b58c.
