### ISSUE TITLE
just change the customView from imageView to UIView,and it does not work!why?

### ISSUE THREAD

**Issue by EnigmaWangek** [jdg/MBProgressHUD#432]
![snip20160919_2](https://cloud.githubusercontent.com/assets/19501391/18624913/aa2b9eca-7e7d-11e6-889f-43de3d50a917.png)

**Comment by EnigmaWangek** [comment]
and I can't never change the customView's size

**Comment by EnigmaWangek** [comment]
In addition:
how to change customView's size ?

**Comment by qingqinghebiancao** [comment]
The document comment has said:
>  The UIView (e.g., a UIImageView) to be shown when the HUD is in MBProgressHUDModeCustomView.
 > The view should implement **intrinsicContentSize** for proper sizing. For best results use approximately 37 by 37 pixels.
 You need to create a new UIView subclass and override its `intrinsicContentSize` method.

**Comment by baight** [comment]
sounds boring! It means that I have to create a new UIView subclass when I want to use 'customView' feature~~~~God help me !
