### ISSUE TITLE
Button always shows

### ISSUE THREAD

**Issue by ShadowLJia** [jdg/MBProgressHUD#435]
`self.hud = [MBProgressHUD showHUDAddedTo:self.navigationController.view
                                    animated:animated];
    # self.hud.button.hidden = YES;
    self.hud.square = YES;`

is the button always shows?

**Comment by wangbiye** [comment]
Find out why?

**Comment by zssr** [comment]
Me too. Have figured it out?
This is how I do it:
```MBProgressHUD *hud = [MBProgressHUD showHUDAddedTo:view animated:YES];
    hud.mode = MBProgressHUDModeText;
    hud.detailsLabel.text = message;
    hud.detailsLabel.font = [UIFont systemFontOfSize:17.f];
    [hud showAnimated:YES];
    [hud hideAnimated:YES afterDelay:duration];```

**Comment by zssr** [comment]
@ShadowLJia  @wangbiye  , hi, I think I find out the reason for this. As comment in the header file `MBProgressHUD.h` of  property `button` says, the button is "Visible only if a target / action is added". 

You can also find the impl of this visibility logic in `-[MBProgressHUDRoundedButton intrinsicContentSize]`. 

I added a breakpoint and executed `po hud.button.allTargets` on the console, it logged this: `{(
    <GrowingUIControlObserver: 0x17021edf0>
)}`. 

So I'm guessing maybe this is the reason for your issue too.

**Comment by stillwalk** [comment]
same issue.Have you solve it ? @zssr 怎么解决的？

**Comment by zssr** [comment]
@stillwalk  , 我用不上那个按钮，然后直接就在 `-[MBProgressHUDRoundedButton intrinsicContentSize]` 中 `return CGSizeZero`

**Comment by stillwalk** [comment]
Thankyou @zssr

**Comment by DeveloperPans** [comment]
thanks, it's work for me.

**Comment by 0xa6a** [comment]
hi, to those who use `GrowingIO`, I have a better solution. Since the button is "visible only if a target / action is added".

`removeTargetsAt(button: hud.button)`


    private static func removeTargetsAt(button: UIButton) {
        for t in button.allTargets {
            button.removeTarget(t, action: nil, for: .allEvents)
        }
    }
