### ISSUE TITLE
 this class is not key value coding-compliant for the key gaussianBlur

### ISSUE THREAD

**Issue by pzee** [jdg/MBProgressHUD#452]
Hello,I use MBProgressHUD (version:1.0.0) in my app,and sometimes it crash.

The log is:
[<__NSArrayI 0x174002730> valueForUndefinedKey:]: this class is not key value coding-compliant for the key gaussianBlur.

-[MBBackgroundView updateForBackgroundStyle] (in xx) (MBProgressHUD.m:1163)

**Comment by pzee** [comment]
This happens in iOS 8.1.1,iOS 8.1.2,iOS 8.1.3. Maybe  the system's bug case it?

**Comment by lexiaoyao20** [comment]
NSUnknownKeyException

[<__NSArrayI 0x15ed1d00> valueForUndefinedKey:]: this class is not key value coding-compliant for the key gaussianBlur.

0 CoreFoundation	___exceptionPreprocess + 127
1 libobjc.A.dylib	objc_exception_throw + 38
2 CoreFoundation	-[NSException init] + 1
3 Foundation	-[NSObject(NSKeyValueCoding) valueForUndefinedKey:] + 263
4 QuartzCore	_CAObject_setValueForKeyPath_ + 1185
5 QuartzCore	-[CALayer setValue:forKeyPath:] + 487
6 UIKit	-[_UIVisualEffectBackdropView _updateInputBounds] + 345
7 UIKit	-[_UIVisualEffectBackdropView _initWithFrame:settings:] + 935
8 UIKit	-[UIVisualEffectView _configureForEffectSettings:] + 143
9 UIKit	-[UIVisualEffectView initWithEffect:] + 121
10 MBProgressHUD	-[MBBackgroundView updateForBackgroundStyle] + 152
11 MBProgressHUD	-[MBBackgroundView initWithFrame:] + 352
12 MBProgressHUD	-[MBProgressHUD setupViews] + 142
13 MBProgressHUD	-[MBProgressHUD commonInit] + 450
14 MBProgressHUD	-[MBProgressHUD initWithFrame:] + 72
15 MBProgressHUD	-[MBProgressHUD initWithView:] + 88
16 MBProgressHUD	+[MBProgressHUD showHUDAddedTo:animated:] + 60
17 Followme	+[MBProgressHUD(FMHUD) showSuccessMessage:inView:delay:] (MBProgressHUD+FMHUD.m:37)
18 Followme	+[MBProgressHUD(FMHUD) showSuccessMessage:inView:] (MBProgressHUD+FMHUD.m:30)

I have the same problem.

**Comment by penoty** [comment]
I have the same problem, too.

**Comment by penoty** [comment]
I have the same problem, too.

**Comment by puyanLiu** [comment]
I have the same problem, too.

**Comment by ixiaogangwyg1** [comment]
I have the same problem, too.

**Comment by matej** [comment]
Looks like a system bug on iOS 8. Other projects are seeing the same. https://github.com/SVProgressHUD/SVProgressHUD/issues/533

Looks like we'd need to use the iOS 7 UIToolbar background workaround on iOS 8 as well to be on the safe side. E.g., convert the relevant `kCFCoreFoundationVersionNumber >= kCFCoreFoundationVersionNumber_iOS_8_0 ` checks to `kCFCoreFoundationVersionNumber >= kCFCoreFoundationVersionNumber_iOS_9_0 ` checks.
