### ISSUE TITLE
MBProgressHUD (~> 0.9)` required by `MWPhotoBrowser (2.1.2)`

### ISSUE THREAD

**Issue by caoyunxiao** [jdg/MBProgressHUD#453]
I found that at the same time use pod 'MWPhotoBrowser', '~ > 2.1.2'Pod 'MBProgressHUD', '~ > 1.0.0, pod complains, I don't know where is the problem
<img width="472" alt="2016-12-22 15 06 38" src="https://cloud.githubusercontent.com/assets/15682437/21417916/b4091e20-c858-11e6-80e8-4145893b5a0f.png">

**Comment by brightsider** [comment]
It's a problem of MWPhotoBrowser

**Comment by caoyunxiao** [comment]
Yes, I think so too

**Comment by LemonChao** [comment]
How do you solve this problem finally？？
it occured to me now. @caoyunxiao

**Comment by ISXue** [comment]
Sorry ，I mistake it by myself!

发自我的 iPhone
