### ISSUE TITLE
_hud.mode = MBProgressHUDModeText

### ISSUE THREAD

**Issue by zhangjianjun056** [jdg/MBProgressHUD#455]
When I use "_hud.mode = MBProgressHUDModeText;"，an error is " Reference to ‘MBProgressHUDModeText’ is ambiguous".

**Comment by zhangjianjun056** [comment]
Can you help me?

**Comment by koenvanderdrift** [comment]
Maybe this can help you: http://stackoverflow.com/questions/25378474/reference-to-x-is-ambiguous ?
