### ISSUE TITLE
Does SVProgressHud work with custom image with animation?

### ISSUE THREAD

**Issue by ramakrishna013** [jdg/MBProgressHUD#461]

**Comment by matej** [comment]
I think you mixed up your HUDs.

**Comment by ramakrishna013** [comment]
@matej I don't understand what you said. Can you explain me a bit clearly.

**Comment by matej** [comment]
Well, you posted a `SVProgressHud` question on the `MBProgressHUD` repository. That's a different component. :)

**Comment by ramakrishna013** [comment]
Do u have an idea on SVProgressHud??
