### ISSUE TITLE
The progress bar color problem

### ISSUE THREAD

**Issue by 627969687** [jdg/MBProgressHUD#463]
In this method(updateViewsForColor) , I see you through "UIAppearance" to ignore the color of the progress bar is set , What is the meaning of doing 

So... I can't set the color
![qq20170315-165029](https://cloud.githubusercontent.com/assets/20868764/23940367/92220ffa-099f-11e7-9056-fe7513e977de.png)

**Comment by matej** [comment]
The `hud.contentColor` overrides this value on MBBarProgressView. That's by design. If you want a custom appearance here you need to create your own bar view. Or override and tweak `updateViewsForColor:`.
