### ISSUE TITLE
Position of MBProgressHUD change

### ISSUE THREAD

**Issue by ACommonChinese** [jdg/MBProgressHUD#468]
Hi, In the stackoverflow, i searched a problem: http://stackoverflow.com/questions/25602009/mbprogresshud-resets-positions-of-uiviews-during-loading

And I did run into a problem something like that. ie, in the controller's view, there is a scroll view, if the scroll view is scrolling, and the MBProgressHUD appear, the position of MBProgressHUD will change compare with previous MBProgressHUD. I think may be it is because the controller's view resets to original position while scroll view is scrolling?

Thanks.

**Comment by matej** [comment]
Can you put up a screencast showing this behavior? Just so we are on the same page. Are you adding MBProgresHUD to your scroll view?
