### ISSUE TITLE
Version conflict between MBProgressHUD and MWPhotoBrowser

### ISSUE THREAD

**Issue by SuAdrenine** [jdg/MBProgressHUD#472]
When I do this:
```
pod 'MBProgressHUD', '~> 1.0.0'
pod 'MWPhotoBrowser'
```

and pod give an error:
```
[!] Unable to satisfy the following requirements:

- `MBProgressHUD (~> 1.0.0)` required by `Podfile`
- `MBProgressHUD (~> 0.9)` required by `MWPhotoBrowser (2.1.2)`
```
but if I change the version of MWPhotoBrowser to 1.2.1,It works ,so, who can tell me whose fault it is? MBProgressHUD or MWPhotoBrowser?
If I want to use the latest version of MBProgressHUD and MWPhotoBrowser , what should I do?

**Comment by matej** [comment]
MBProgressHUD is a dependency here there's nothing we can do about it here. You might want to update MBProgressHUD in MWPhotoBrowser.
