### ISSUE TITLE
The latest set of hud.activityIndicatorColor method is invalid.

### ISSUE THREAD

**Issue by MorningStarJ** [jdg/MBProgressHUD#473]
When I using the previous methods '[ hud.activityIndicatorColor]'  there are some 'warning'.But if I using the lastest method(Xcode gives me) to setup this method there is no effect.How should I setup this?

**Comment by matej** [comment]
How can this be reproduced? UIAppearance appears to be working fine in the demo app. https://github.com/jdg/MBProgressHUD/issues/475#issuecomment-343735800

**Comment by PauliusVindzigelskis** [comment]
Try in Swift. In Swift, it says that 'color' is deprecated

**Comment by uncleRX** [comment]
it's belong to  property  " bezelView's subView
