### ISSUE TITLE
setting bezelView backgroundView is not working

### ISSUE THREAD

**Issue by xuhongfei** [jdg/MBProgressHUD#474]
`  MBProgressHUD *hud = [MBProgressHUD showHUDAddedTo:view animated:YES];
    hud.mode = MBProgressHUDModeCustomView;
    
    hud.customView = [[UIImageView alloc] initWithImage:[UIImage imageNamed:@"0"]];
    
    hud.bezelView.backgroundColor = [UIColor blackColor];
    hud.bezelView.alpha = .76f;
    hud.bezelView.style = MBProgressHUDBackgroundStyleSolidColor;
    hud.label.text = text;
    hud.label.textColor = UIColorFromRGB(0xffda44);
    
    hud.detailsLabel.text = detailsText;
    hud.detailsLabel.textColor = UIColorFromRGB(0xffffff);
    
    hud.removeFromSuperViewOnHide = YES;
    
    [hud hideAnimated:YES afterDelay:afterDelay];`

hud.bezelView background color always is white color.

**Comment by winterWD** [comment]
try 
```
hud.bezelView.color = [UIColor blackColor];
```

**Comment by xuhongfei** [comment]
@winterWD That's right. ths!
