### ISSUE TITLE
UIActivityIndicatorView appearanceWhenContainedIn color not working on iPad

### ISSUE THREAD

**Issue by hawkeye1194** [jdg/MBProgressHUD#475]
[UIActivityIndicatorView appearanceWhenContainedInInstancesOfClasses:@[[MBProgressHUD class]]].color = [UIColor colorWithRed:0.357 green:0.365 blue:0.365 alpha:1.00]; is not working on the iPad. It is using the default activity indicator color. I do not have any issues on iPhone setting the color this way. Running iOS 9.3.5 on an iPad 2.

**Comment by matej** [comment]
I modified the example project in the following way and could not reproduce the issue. Using the iPhone or iPad made no difference. 

<img width="2672" alt="screen shot 2017-11-12 at 14 01 34" src="https://user-images.githubusercontent.com/91322/32699198-2dccebf2-c7b2-11e7-9075-a23081326cf0.png">
