### ISSUE TITLE
Dropbox images gone

### ISSUE THREAD

**Issue by EternalBlack** [jdg/MBProgressHUD#478]
Not a real problem/bug, but it seems like you lately removed the images from your dropbox. They are not visible on the github-readme anymore.

**Comment by matej** [comment]
Thanks for the ping. The images are still there, but I lost the public folder when dowgrading from Dropbox Pro. Migrated them to GitHub. 

Fixed in https://github.com/jdg/MBProgressHUD/commit/a7c3601fbd58946c9dc0892ab9394f2e1f3c4d89
