### ISSUE TITLE
Is there a way to check if a hud is already being shown?

### ISSUE THREAD

**Issue by robertofrontado** [jdg/MBProgressHUD#481]

**Comment by shubh10** [comment]
Try this HUD library for iOS in swift https://github.com/shubh10/JustHUD

**Comment by matej** [comment]
@shubh10 Please don't spam. You posted the same message in a bunch of threads. 

@robertofrontado `BOOL showing = hud.alpha > 0.f`.

**Comment by shubh10** [comment]
@matej sure, do try though
