### ISSUE TITLE
remove from superview error on iOS 11

### ISSUE THREAD

**Issue by 907064772** [jdg/MBProgressHUD#482]
+ (MBProgressHUD *)HUDForView:(UIView *)view {
    NSEnumerator *subviewsEnum = [view.subviews reverseObjectEnumerator];
    for (UIView *subview in subviewsEnum) {
        if ([subview isKindOfClass:self]) {
            return (MBProgressHUD *)subview;
        }
    }
    return nil;
}

this method can not get subviews

**Comment by matej** [comment]
Erm? What's wrong? Works just fine here.

**Comment by matej** [comment]
Possible that that the main thread checker is kicking in if you are calling this from a background thread.
