### ISSUE TITLE
I use MBProgressModeText ,but is show activityIndicator first 

### ISSUE THREAD

**Issue by hxyShawn** [jdg/MBProgressHUD#486]
As title said,it shows activityIndicator first then show title ,and if I click again ,it show only text

my code:
+ (MBProgressHUD *)hxy_showTextHUDAddedTo:(UIView *)view labelText:(NSString *)labelText detailText:(NSString *)detailText labelFont:(UIFont *)labelFont labelColor:(UIColor *)labelColor detailFont:(UIFont *)detailFont detailColor:(UIColor *)detailColor opacity:(CGFloat)opacity delay:(NSTimeInterval)delay
{
    static MBProgressHUD *HUD = nil;
    if (HUD) {
        [HUD hide:YES];
        HUD  = nil;
    }
    //MBProgressHUD 默认字体颜色白色
    HUD = [MBProgressHUD showHUDAddedTo:view animated:YES];
    HUD.labelText = labelText;
    HUD.detailsLabelText = detailText;
    HUD.labelColor = labelColor?labelColor:[UIColor whiteColor];
    HUD.detailsLabelColor = detailColor?detailColor:[UIColor whiteColor];
    HUD.labelFont = labelFont?labelFont:[UIFont boldSystemFontOfSize:16.f];
    HUD.detailsLabelFont = detailFont?detailFont:[UIFont boldSystemFontOfSize:12.f];
    HUD.opacity = opacity?opacity:0.8;
    HUD.mode = MBProgressHUDModeText;
    [HUD show:YES];
    if (delay <= 0) {
        [HUD hide:YES afterDelay:1.5];
    }
    return HUD;
}

**Comment by shubh10** [comment]
Try this HUD library for iOS in swift https://github.com/shubh10/JustHUD

**Comment by matej** [comment]
I tired this in the demo project and it worked as expected with the latest version.
