### ISSUE TITLE
How can I disable the navigation when mbprogress is showing

### ISSUE THREAD

**Issue by santhoshs5** [jdg/MBProgressHUD#489]
var HUD: MBProgressHUD {
        unowned let unownedself = self
        let progressHUD = MBProgressHUD(view: unownedself.view)
        progressHUD.bezelView.color = UIColor.clear
        progressHUD.backgroundView.style = .blur
        //progressHUD.dimBackground = true
        view.addSubview(progressHUD)
        return progressHUD
    }

Above is my code.

**Comment by shubh10** [comment]
Try this HUD library for iOS in swift https://github.com/shubh10/JustHUD

**Comment by matej** [comment]
Depends on the navigation you have set up. Normally you do that with code unrelated to MBProgressHUD. But you can also add the HUD to your window to block all touches. `view.window.addSubview(progressHUD)`.
