### ISSUE TITLE
Xcode 9 Beta 3/iOS 11 Beta Warnings

### ISSUE THREAD

**Issue by hawkeye1194** [jdg/MBProgressHUD#490]
Attached are images with the warnings using Xcode 9 beta 3 and iOS 11.

<img width="1181" alt="screen shot 2017-07-19 at 9 59 51 am" src="https://user-images.githubusercontent.com/15990396/28379602-1ef53dd6-6c69-11e7-807d-712c3911b9a1.png">
<img width="1204" alt="screen shot 2017-07-19 at 10 00 13 am" src="https://user-images.githubusercontent.com/15990396/28379603-1efd64a2-6c69-11e7-90d8-1b95c1cc140a.png">

**Comment by Kjuly** [comment]
Seems latest source code has fixed it.

https://github.com/jdg/MBProgressHUD/blob/master/MBProgressHUD.h#L72
https://github.com/jdg/MBProgressHUD/blob/master/MBProgressHUD.m#L1282

Suggest to close it. :)
