### ISSUE TITLE
isUserInteractionEnabled not Working in Swift 3.0

### ISSUE THREAD

**Issue by ImanX** [jdg/MBProgressHUD#492]
Hello guys!
I use this lib in Swift 3.0 and i want disable any action from user when MBProgresHUD is Showing!
I called isUserInteractionEnabled = false but not work.
What's problem?
Thank for help.

**Comment by Bo98** [comment]
You actually want `isUserInteractionEnabled = true`. It's confusing at first, but it's because the setting refers to the HUD itself, so allowing interaction with the HUD means that it doesn't let interaction go through it (i.e. it handles interaction itself and blocks it from going further).
