### ISSUE TITLE
How to change items padding

### ISSUE THREAD

**Issue by CaiChenghan** [jdg/MBProgressHUD#494]
![image](https://user-images.githubusercontent.com/9568389/29298881-8fa0019e-819d-11e7-858f-05cab975a71c.png)
Hi,how can i change the padding of the items. About distance of titleLabel'bottom and detailsLabel'top. Just like the image'code **MBDefaultPadding** i want change it when i use.

**Comment by matej** [comment]
`margin` is the only related property in the public API. For detailed customizations you need subclass and to override the layout code.
