### ISSUE TITLE
-Wstrict-prototypes cause compile time error.

### ISSUE THREAD

**Issue by luliu** [jdg/MBProgressHUD#496]
Xcode Version 9.0 beta 6 (9M214v)

MBProgressHUD.h compiler warning on line 72:
`typedef void (^MBProgressHUDCompletionBlock)();`    <- This block declaration is not a prototype

**Comment by matej** [comment]
`typedef void (^MBProgressHUDCompletionBlock)(void);`

**Comment by rbaumbach** [comment]
It looks like this has been updated on the `master` branch.  I've opened an issue to get this out on a new release [Github Issue #498](https://github.com/jdg/MBProgressHUD/issues/498)

**Comment by kikolobo** [comment]
Can someone release it on cocoapods please?

**Comment by matej** [comment]
This is fixed on master. You can set cocoa pods to fetch a specific commit until a new version is available. 

https://guides.cocoapods.org/using/the-podfile.html#from-a-podspec-in-the-root-of-a-library-repo

Will try to do an update later this week.

**Comment by chrisvanbuskirk** [comment]
The problem with that solution is other podspec's can't point to a commit. ^
