### ISSUE TITLE
New release soon?

### ISSUE THREAD

**Issue by rbaumbach** [jdg/MBProgressHUD#498]
I'm attempting to update my projects to use Xcode 9 to get ready for iOS 11.  When attempting to build using the latest version of MBProgressHUD, version `1.0.0`, it complains about not using `(void)` instead of `()`(empty params) for block params.

I noticed that this has been addressed on the `master` branch.  Is it possible to create a new release (tag) soon that contains this so I won't have to lock our MBProgressHUD dependency to a git SHA?

**Comment by jordanbigel** [comment]
It would be great if the CocoaPod was also updated with this fix. Is that in the works?

**Comment by Ewg777** [comment]
@jdg any chance to update the podspec this year?

**Comment by matej** [comment]
A new version has now been released to cocoapods.
