### ISSUE TITLE
HUD is not show when the keyboard is editing in iOS 11 ?

### ISSUE THREAD

**Issue by tiancl16** [jdg/MBProgressHUD#500]
In the textfield, When I have enter text incorrect in iOS11.0,  HUD is not show, why ?

**Comment by kedu** [comment]
是啊,我这个也是不显示了.顶起来.

**Comment by Nslogdql** [comment]
MB作者好像潜水了啊，应该适配一下啊，菊花一直转，调用hide都不行

**Comment by freishya** [comment]
![screen shot 2017-09-25 at 11 36 47 am](https://user-images.githubusercontent.com/25956040/30792601-e2943150-a1e5-11e7-8df2-fb44bfbe3770.png)

IOS 11 get minor error. Thank's

**Comment by WangLiangMin** [comment]
我的只在刚装上程序时显示一次，然后就再也不出现了，好多项目都是用的 MB，要愁坏了

**Comment by yangqilong** [comment]
一样

**Comment by Brances** [comment]
iphone 8  iOS 11 也不显示

**Comment by Manloff** [comment]
@tiancl16 是否使用了 MBProgress + mj? ios11上显示要指定view--show:"" toView:self.navigationController.view

**Comment by EdgarDegas** [comment]
If you are using MBProgress + MJ, call
`[MBProgressHUD showError:toView:] `
instead.

**Comment by suqinglin113x** [comment]
ios11 windows层变了吧，我是改了源码添加到keywindow层

**Comment by Brances** [comment]
@suqinglin113x 确实是层级变了，加到这里 ：[UIApplication sharedApplication].keyWindow  就可以了

**Comment by matej** [comment]
Closing this. Please reopen with detailed reproduction steps in English if this is an MBProgressHUD specific issue.
