### ISSUE TITLE
can not hide in iOS 11

### ISSUE THREAD

**Issue by lck93** [jdg/MBProgressHUD#502]

**Comment by lck93** [comment]
it can not hide in iOS11,need help

**Comment by luo-h** [comment]
菊花背景怎么是白色的，怎么改成以前的黑色啊

**Comment by cpvbruno** [comment]
neither do I :(

**Comment by Manloff** [comment]
add and remove hud in the mainThread @lck93 @cpvbruno

**Comment by lck93** [comment]
嗯嗯

**Comment by cpvbruno** [comment]
Thanks @Manloff I solved using: 
`DispatchQueue.main.async {
            self.stopLoading() //my function to stop loading
        }`

**Comment by lilin87788** [comment]
can not hide in ios11
