### ISSUE TITLE
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'MBProgressHUD needs to be accessed on the main thread.

### ISSUE THREAD

**Issue by Nayab14** [jdg/MBProgressHUD#505]
hi i am facing the issue on MBProgressHud.m  in the following method 

+ (MBProgressHUD *)HUDForView:(UIView *)view {
    NSEnumerator *subviewsEnum = [view.subviews reverseObjectEnumerator];
    for (UIView *subview in subviewsEnum) {
        if ([subview isKindOfClass:self]) {
            return (MBProgressHUD *)subview;
        }
    }
    return nil;
}
 
in this line afte assertion failure:
NSEnumerator *subviewsEnum = [view.subviews reverseObjectEnumerator];

**Comment by matej** [comment]
> MBProgressHUD needs to be accessed on the main thread.

This means that you are using HUD methods that are meant to be accessed on the main thread on a different thread. That's likely an issue in your code. Check your threading code. 

https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Multithreading/Introduction/Introduction.html
