### ISSUE TITLE
Please, update screenshots of hud and provide description how to get old-style hud (black hud with white spinner) without long efforts to customise it properly

### ISSUE THREAD

**Issue by igorkislyuk** [jdg/MBProgressHUD#506]

**Comment by matej** [comment]
Screenshots have been updated. If you don't want to spend time customizing the new appearance you can check out the [legacy branch](https://github.com/jdg/MBProgressHUD/tree/legacy).

**Comment by igorkislyuk** [comment]
Thank you. I deal with customisation ;) It seems screenshot are still broken. :(
