### ISSUE TITLE
Fix `+ (MBProgressHUD *)HUDForView:(UIView *)view` for Swift

### ISSUE THREAD

**Issue by Arror** [jdg/MBProgressHUD#543]
This method will be mapped to a convenience constructor in Swift.

```swift
if let hud = MBProgressHUD.init(for: self.base.view) {
    return hud
} else {
    let hud = MBProgressHUD()
    self.base.view.addSubview(hud)
    return hud
}
```

**Comment by merkury** [comment]
well HUDForView did something different: it searches through all subviews, if one is a MBProgressHUD .  This is important i.e. if you want to know if a MBProgressHUD is already shown. 
So I am still missing this function in swift. See my comment in https://github.com/jdg/MBProgressHUD/issues/450 as well.
