### ISSUE TITLE
Set CustomView，but there is effectView behind the customView

### ISSUE THREAD

**Issue by robinvpersie** [jdg/MBProgressHUD#554]
I set areDefaultMotionEffectsEnabled = false，but it cannot work
![wechatimg430](https://user-images.githubusercontent.com/8272414/49015308-442d6380-f1b5-11e8-9a4b-07af879e65ab.jpeg)

**Comment by zhangjirui** [comment]
`        _hud.bezelView.style = MBProgressHUDBackgroundStyleSolidColor;
        _hud.bezelView.color = [UIColor clearColor];`
