### ISSUE TITLE
The subclasses of MBProgressHUD  can't hide

### ISSUE THREAD

**Issue by daishuyi** [jdg/MBProgressHUD#559]
NXProgressHUD extends MBProgressHUD,  NXProgressHUD hide the MBProgressHUD Object，can't hide.  
The reson：
+ (MBProgressHUD *)HUDForView:(UIView *)view {
    NSEnumerator *subviewsEnum = [view.subviews reverseObjectEnumerator];
    for (UIView *subview in subviewsEnum) {
        **// _here, [subview isKindOfClass:self] return false,  [subview isKindOfClass:MBProgressHUD.class] return true_**
        if ([subview isKindOfClass:self]) {
            MBProgressHUD *hud = (MBProgressHUD *)subview;
            if (hud.hasFinished == NO) {
                return hud;
            }
        }
    }
    return nil;
}

**Comment by matej** [comment]
How is this method called? I guess it's called via `+[NXProgressHUD HUDForView:]`, but the actual object is just a `MBProgressHUD` and not a `NXProgressHUD` instance. In so far this makes sense.
