### ISSUE TITLE
Hud (sometimes) shows a button with empty title on its own.

### ISSUE THREAD

**Issue by alperkayabasi** [jdg/MBProgressHUD#561]
I don't set a target or anything. Only code I called is [MBProgressHUD showHUDAddedTo:self.view animated:YES]

![image](https://user-images.githubusercontent.com/2501751/51912635-d89a8900-23e5-11e9-8e68-399f891eece3.png)

**Comment by yanqiuLove** [comment]
Have you solved this problem? I have the same problem. I hope to get your help. Thank you very much

**Comment by yanqiuLove** [comment]
应该是你引用的其他三方库添加了监听事件，你可以使用遍历子控件的方式，将MBProgressHUDRoundedButton的事件移除我是这样处理的：
+ (void)hideMBProgressHUDRoundedButtonWithHUD:(MBProgressHUD *)hud {
    for (UIView *childView in hud.subviews) {
        NSString *bgViewClassStr = [NSString stringWithFormat:@"%@",childView.class];
        if ([bgViewClassStr isEqualToString:@"MBBackgroundView"]) {
            for (UIView *bgChildView in childView.subviews) {
                NSString *bgChildViewClassStr = [NSString stringWithFormat:@"%@",bgChildView.class];
                if ([bgChildViewClassStr isEqualToString:@"MBProgressHUDRoundedButton"]) {
                    UIButton *button = (UIButton *)bgChildView;
                    [button removeTarget:nil action:nil forControlEvents:UIControlEventAllEvents];
                }
            }
        }
    }
}
这里遍历两次是因为第一层遍历只能得到两个MBBackgroundView对象，无法获取到MBProgressHUDRoundedButton对象，我暂时是这样修复的，如果你有其他好的方式还希望能够互相交流学习。

**Comment by yanqiuLove** [comment]
[hud.button removeTarget:nil action:nil forControlEvents:UIControlEventAllEvents];

**Comment by roarapps** [comment]
> [hud.button removeTarget:nil action:nil forControlEvents:UIControlEventAllEvents];

Doesn't remove it.

Also have same issue

**Comment by yanqiuLove** [comment]
> > [hud.button removeTarget：nil action：nil forControlEvents：UIControlEventAllEvents];
> 
> 不删除它。
> 
> 也有同样的问题

You'll need to check if any of the other third-party libraries have added methods to their hud objects, and you'll want to use this method first:

hud. Button. Hidden = YES;
[hud. Button removeTarget: nil action: nil forControlEvents: UIControlEventAllEvents];


If this method can not solve your problem, you can also use traverse all child controls of the hud object, find MBProgressHUDRoundedButton object, and then use : 
[button removeTarget: nil action: nil forControlEvents: UIControlEventAllEvents];


At present, I can think of only these two methods. If you have a better solution, I hope we can communicate with each other~

**Comment by roarapps** [comment]
Thank You!  hud. Button. Hidden = YES; seems to have done the trick. Not sure what is setting it to true in the first place :(

**Comment by alperkayabasi** [comment]
@roarapps The thing is, I don't know why we need to set button.hidden = YES in the first place. It should already be hidden if you don't set a target. And using that code means we need to keep a variable for every HUD we use.

That's not a great solution. I stopped using this framework for now.

**Comment by matej** [comment]
This should be fixed now. See https://github.com/jdg/MBProgressHUD/issues/587.
