### ISSUE TITLE
The First show, It takes 8 seconds!

### ISSUE THREAD

**Issue by IPOSDai** [jdg/MBProgressHUD#569]
CFAbsoluteTime startTime = CFAbsoluteTimeGetCurrent();
        
        MBProgressHUD *hud = [MBProgressHUD showHUDAddedTo:container animated:YES];
        hud.mode = MBProgressHUDModeCustomView;
        hud.customView = [[UIImageView alloc] initWithImage:[UIImage imageNamed:@"create_close"]];
        hud.detailsLabel.text = message;
        hud.detailsLabel.font = [UIFont systemFontOfSize:15];
        
        [hud hideAnimated:YES afterDelay:2.f];
        
        CFAbsoluteTime endTime = CFAbsoluteTimeGetCurrent();
        NSLog(@"执行时间： %f", endTime - startTime);

and the "Main Thread Checker" on. it is normal when the "Main Thread Checker" off.

**Comment by Zhanggaoyi92** [comment]
run 
- commonInit
  - setupViews
    - updateBezelMotionEffects
       - [bezelView addMotionEffect:group];
here , show error :
Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 2405, TID: 598069, Thread name: com.apple.CoreMotion.MotionThread, Queue name: com.apple.root.default-qos.overcommit, QoS: 0

but [NSThread currentThread] show it's on main thread.

**Comment by helisHuZ** [comment]
I have also appeared this problem, can I only turn off the "Main Thread Checker"?

**Comment by ruixingchen** [comment]
meet this problem,too, but strange:
on my iPhoneX 12.3.1 it works well
on my iPhoneXR 12.2, it just stuck for seconds and reports the Main Thread Checker

**Comment by ruixingchen** [comment]
@helisHuZ problem fixed after I turned it off

**Comment by elenx** [comment]
me too.

Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 21307, TID: 1519504, Thread name: com.apple.CoreMotion.MotionThread, Queue name: com.apple.root.default-qos.overcommit, QoS: 0
Backtrace:
4   libobjc.A.dylib                     0x00000001906936f4 <redacted> + 56
5   CoreMotion                          0x0000000196e0dd9c CoreMotion + 294300
6   CoreMotion                          0x0000000196e0e2cc CoreMotion + 295628
7   CoreMotion                          0x0000000196e0e1dc CoreMotion + 295388
8   CoreMotion                          0x0000000196e3c01c CoreMotion + 483356
9   CoreMotion                          0x0000000196e3c060 CoreMotion + 483424
10  CoreFoundation                      0x000000019142227c <redacted> + 28
11  CoreFoundation                      0x0000000191421b64 <redacted> + 276
12  CoreFoundation                      0x000000019141ce58 <redacted> + 2276
13  CoreFoundation                      0x000000019141c254 CFRunLoopRunSpecific + 452
14  CoreFoundation                      0x000000019141cf88 CFRunLoopRun + 84
15  CoreMotion                          0x0000000196e3b9f4 CoreMotion + 481780
16  libsystem_pthread.dylib             0x000000019109a908 <redacted> + 132
17  libsystem_pthread.dylib             0x000000019109a864 _pthread_start + 48
18  libsystem_pthread.dylib             0x00000001910a2dcc thread_start + 4
2019-06-04 15:10:57.912995+0800 Project[21307:1519504] [reports] Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 21307, TID: 1519504, Thread name: com.apple.CoreMotion.MotionThread, Queue name: com.apple.root.default-qos.overcommit, QoS: 0
Backtrace:
4   libobjc.A.dylib                     0x00000001906936f4 <redacted> + 56
5   CoreMotion                          0x0000000196e0dd9c CoreMotion + 294300
6   CoreMotion                          0x0000000196e0e2cc CoreMotion + 295628
7   CoreMotion                          0x0000000196e0e1dc CoreMotion + 295388
8   CoreMotion                          0x0000000196e3c01c CoreMotion + 483356
9   CoreMotion                          0x0000000196e3c060 CoreMotion + 483424
10  CoreFoundation                      0x000000019142227c <redacted> + 28
11  CoreFoundation                      0x0000000191421b64 <redacted> + 276
12  CoreFoundation                      0x000000019141ce58 <redacted> + 2276
13  CoreFoundation                      0x000000019141c254 CFRunLoopRunSpecific + 452
14  CoreFoundation                      0x000000019141cf88 CFRunLoopRun + 84
15  CoreMotion                          0x0000000196e3b9f4 CoreMotion + 481780
16  libsystem_pthread.dylib             0x000000019109a908 <redacted> + 132
17  libsystem_pthread.dylib             0x000000019109a864 _pthread_start + 48
18  libsystem_pthread.dylib             0x00000001910a2dcc thread_start + 4

**Comment by elenx** [comment]
see [#552](https://github.com/jdg/MBProgressHUD/issues/552)

**Comment by matej** [comment]
Closing since #552 is resolved.
