### ISSUE TITLE
The API is too difficult to use

### ISSUE THREAD

**Issue by steve7688** [jdg/MBProgressHUD#570]
maybe it is a great library

But is it too bloated?

and the default UI is worse than the old version

**Comment by wuwenju** [comment]
yes,you are right.

**Comment by matej** [comment]
Well, there are some alternatives out there that you can use instead. Some have simpler APIs. It's an old library and it tries to maintain some backwards capability. 

The UI can be customized and there's also a legacy branch for the old version if you prefer that. 

This is not an actionable ticket so I'm closing it.
