### ISSUE TITLE
Support for iOS 13 Dark Mode

### ISSUE THREAD

**Issue by jhammer** [jdg/MBProgressHUD#577]
Just curious if support for iOS 13 Dark Mode is planned in the near term, or if that is something you're looking for a PR on. Thanks!

**Comment by inoryshu** [comment]
暗黑模式，你自己换个背景颜色不就行了？完全可以自己搞呀！

**Comment by jhammer** [comment]
暗黑模式不会那么简单，需要使用新iOS 13 API。参见： https://developer.apple.com/videos/play/wwdc2019/214/

**Comment by inoryshu** [comment]
我认为你想复杂了！

**Comment by inoryshu** [comment]
![image](https://user-images.githubusercontent.com/16499387/61774223-ff7fc800-ae28-11e9-8a4b-7461a22b40dc.png)
自适应配色，你认为有多复杂？HUD显示的颜色样式除非你用默认的，不然你都可以自己设置！

**Comment by jhammer** [comment]
好像你还没有看我上面提到的视频。暗黑模式跟UIBlurEffect和UIVisualEffectView也有关系。

**Comment by inoryshu** [comment]
现在就有iOS13beta版，你可以试试看。

**Comment by inoryshu** [comment]
另外看啥视频呀，直接看文档：
![image](https://user-images.githubusercontent.com/16499387/61840691-9352a200-aec4-11e9-94fa-b281c1393bfe.png)
这张图应该算是最简单明了的了吧？UIBlurEffect和UIVisualEffectView这个是做高斯模糊效果的呀，你没做过吗？

**Comment by inoryshu** [comment]
![image](https://user-images.githubusercontent.com/16499387/61840758-d1e85c80-aec4-11e9-8064-eea06dfdf28a.png)

**Comment by jhammer** [comment]
视频和文档我早已读完了。MBProgressHUD已经使用者UIBlurEffect和UIVisualEffectView，但是还没升级到iOS 13兼容的material。因为不知道 @jdg 有没有升级的计划，所以我开此issue问问。

**Comment by inoryshu** [comment]
哦。明白了。你说的就是blurEffectStyle问题吧？
![image](https://user-images.githubusercontent.com/16499387/61842545-2ee71100-aecb-11e9-8476-daa6784d27c7.png)
这个吧？你应该也可以自己设置的。他目前默认是UIBlurEffectStyleLight，你是想让他改这个？

**Comment by jhammer** [comment]
对，但也要考虑到语义化颜色（包括CGColor）的问题。这些都是我自己改造的，但我在等 @jdg 的回答。

**Comment by odedDilmoni** [comment]
Hi 
Can you add iOS13 dark mode support?

**Comment by matej** [comment]
1.2.0 improves this. If something is still off, please open dedicated followup tickets.
