### ISSUE TITLE
Ask for advice

### ISSUE THREAD

**Issue by flyOfYW** [jdg/MBProgressHUD#580]
Why, whenever you use UIView animateWithDuration-related methods, you automatically call the -(void) animateIn:(BOOL) animating In withType:(MBProgress HUDAnimation) type completion:(void(^) (BOOL finished)
<img width="1310" alt="WX20190814-182923@2x" src="https://user-images.githubusercontent.com/17938752/63014954-5164bc80-bec2-11e9-93a6-aee40a72dc16.png">
![Uploading WX20190814-183047@2x.png…]()
![Uploading WX20190814-183101@2x.png…]()

**Comment by flyOfYW** [comment]
@jdg

**Comment by matej** [comment]
I don't really follow. What's the problem here?
