### ISSUE TITLE
Progress Indicator not centered in iOS 13

### ISSUE THREAD

**Issue by moyitpro** [jdg/MBProgressHUD#583]
The progress indicator is not centered when the HUD control is shown in iOS 13
![original](https://user-images.githubusercontent.com/161183/67307115-f94fc500-f4c5-11e9-8e96-ef30520bd335.jpg)

**Comment by matej** [comment]
Can you provide reproduction steps for this in the demo project that's part of this repository? I can't reproduce this. 

![Simulator Screen Shot - iPhone 11 Pro - 2020-01-13 at 22 56 36](https://user-images.githubusercontent.com/91322/72295517-065cfa00-3658-11ea-8382-ffdd72bfff31.png)

**Comment by moyitpro** [comment]
I can't produce it in the demo app. However, in my app with the updated MBProgressHud, it does not appear properly.

<img width="1194" alt="Screenshot 2020-01-13 at 7 43 14 PM" src="https://user-images.githubusercontent.com/161183/72303962-08fe2600-363d-11ea-9c46-e037bb332149.png">

The code is similar to the demo, not sure what I am doing wrong. 

```objective-c
 if (show && !_refreshing) {
        _hud = [MBProgressHUD showHUDAddedTo:self.view animated:YES];
        _hud.label.text = @"Loading";
        if (@available(iOS 13, *)) { }
        else {
            _hud.bezelView.blurEffectStyle = [NSUserDefaults.standardUserDefaults boolForKey:@"darkmode"] ? UIBlurEffectStyleDark : UIBlurEffectStyleLight;
            _hud.contentColor = [ThemeManager sharedCurrentTheme].textColor;
        }
        _refreshing = YES;
    }
    else if (!show) {
        [_hud hideAnimated:YES];
        _refreshing = NO;
    }
    _titleinfobaritem.enabled = !show;
    _shareitembaritem.enabled = !show;
    _optionsitembaritem.enabled = !show;```

**Comment by matej** [comment]
Is self.view a table view? I'd not recommend putting the HUD on a table view (see the Readme). 

Other than that, I's going to be hard for me to reason about this without concrete reproduction steps in the example or an isolated sample. If you manage to get any more information please feel free to update this ticket or open a PR.

**Comment by moyitpro** [comment]
I figured out the problem. The library FrameAccessor was causing the issue. I created a subclass for UIView and have the library point to that subclass so that library won't interfere with all the views, only the libraries that need FrameAccessor
