### ISSUE TITLE
Add shadow effect to customView, but failed.

### ISSUE THREAD

**Issue by min554357332** [jdg/MBProgressHUD#586]
What should I do?

**Comment by min554357332** [comment]
Adding a custom view with shadow effect to self.view is successful. But it failed in hud.customview.

**Comment by matej** [comment]
Sorry, but I think this classifies as personal support. Please see: https://github.com/jdg/MBProgressHUD/blob/master/CONTRIBUTING.md#using-the-issue-tracker
