### ISSUE TITLE
Conflict with FBSDKCoreKit(5.12.0), will show empty Button (MBProgressHUDRoundedButton)

### ISSUE THREAD

**Issue by zaishihuang** [jdg/MBProgressHUD#587]
Conflict with FBSDKCoreKit(5.12.0), will show empty Button (MBProgressHUDRoundedButton)
Please see the screenshot
![hud3](https://user-images.githubusercontent.com/5444790/70421540-eb212c80-1aa4-11ea-9d52-3151dc2aabc6.png)
![hud1](https://user-images.githubusercontent.com/5444790/70421550-f1170d80-1aa4-11ea-83b9-d317b639407c.png)
![hud2](https://user-images.githubusercontent.com/5444790/70421559-f411fe00-1aa4-11ea-9b53-bc1c1c4a3dbf.png)

**Comment by Ptbaileys** [comment]
same problem

**Comment by rojo69** [comment]
Same here. FB swizzles and adds a target (control event).

**Comment by Ptbaileys** [comment]
I don't use this btn. If u want try comment all MBProgressHUDRoundedButton.

**Comment by zaishihuang** [comment]
MBProgressHUDRoundedButton set hidden Yes and in intrinsicContentSize implementation, modify like this:
if (self.hidden || self.allControlEvents == 0) return CGSizeZero;

can fix the problem.

**Comment by kittu4ios** [comment]
I am also facing the same issue.  if (self.hidden || self.allControlEvents == 0) return CGSizeZero; fixed my problem. But I am using cocoa pods. In there any way to fix this issue without modifying cocoa pods file

**Comment by matej** [comment]
Should be fixed in #588. If not please reopen.
