### ISSUE TITLE
MBProgressHUD IOS 13 Indeterminate Color 

### ISSUE THREAD

**Issue by wujunyang** [jdg/MBProgressHUD#595]
MBProgressHUD in IOS 13  Changing Indeterminate color has no effect ；It works normally in other system versions

[UIActivityIndicatorView appearanceWhenContainedInInstancesOfClasses:@[[MBProgressHUD class]]].color = [UIColor redColor];

**Comment by zenglk** [comment]
you can set contentColor to resolve

**Comment by wtg934614282** [comment]
How  to set MBProgressHUD IOS 13 Indeterminate  backColor

**Comment by wujunyang** [comment]
@wtg934614282 

+ (MBProgressHUD *)showProgressToView:(UIView *)view Text:(NSString *)text{
    if (view == nil) view = (UIView*)[UIApplication sharedApplication].delegate.window;
    MBProgressHUD *hud = [MBProgressHUD showHUDAddedTo:view animated:YES];
    hud.label.text=text;
    hud.bezelView.style = MBProgressHUDBackgroundStyleSolidColor;
    hud.bezelView.backgroundColor = [UIColor clearColor];
    hud.bezelView.alpha=0.8;
    hud.label.font=REGULAR_FONT(15);
    
    if (@available(iOS 13.0, *)) {
        for (UIView *vyActivityIndicatorView in hud.bezelView.subviews) {
            if ([vyActivityIndicatorView isKindOfClass:[UIActivityIndicatorView class]]) {
                ((UIActivityIndicatorView *)vyActivityIndicatorView).color=VY_Color_Green_07DB7F;
                break;
            }
        }
    }
    //hud.dimBackground = NO;
    return hud;
}

**Comment by NameIsFGJ** [comment]
hud.bezelView.style = MBProgressHUDBackgroundStyleSolidColor;

**Comment by NameIsFGJ** [comment]
you can set this : hud.bezelView.style = MBProgressHUDBackgroundStyleSolidColor;

**Comment by wtg934614282** [comment]
ok，thanks

------------------ Original ------------------
