### ISSUE TITLE
MBProgressHUD source change?

### ISSUE THREAD

**Issue by xingheng** [jdg/MBProgressHUD#622]
I just found the source in podspec change to matej's fork? Is that on purpose?

https://github.com/jdg/MBProgressHUD/blob/c843e4c86d320a11552898646effa8000042ab16/MBProgressHUD.podspec#L14

Confirm: 
1. Does that mean this repo just transfer to another owner? I didn't find any descriptions on this in README and change log file.
2. If yes of 1, will the existing issues and prs will be resolved?
3. If no of 1, is the original repo get hacked?
4. Is it still under maintenance?

@jdg ?

**Comment by matej** [comment]
https://github.com/jdg/MBProgressHUD/blob/c843e4c86d320a11552898646effa8000042ab16/LICENSE#L1

If you check the Git history you'll see that this entry was there from the start. I keep both repos in sync.

**Comment by xingheng** [comment]
Gotcha
