### ISSUE TITLE
Apple Privacy Manifest

### ISSUE THREAD

**Issue by manahilov** [jdg/MBProgressHUD#647]
Hi team,
Is there a plan to include the PrivacyInfo.xcprivacy manifest as required by Apple?
ref: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

Thanks,
Boyan

**Comment by LionWY** [comment]
+1

**Comment by zeroskylian** [comment]
https://developer.apple.com/support/third-party-SDK-requirements/

**Comment by brendand** [comment]
+1

**Comment by zziazm** [comment]
+1

**Comment by 379800792** [comment]
+1

**Comment by CH3COOH** [comment]
Hello!
Does anyone know which API used in MBProgressHUD is problematic?

**Comment by threema-matteo** [comment]
Hey @jdg , are there any updates on this?

**Comment by liam-i** [comment]
I made a Swift version of the HUD.
https://github.com/liam-i/HUD

Thanks a lot to [Jonathan George](https://github.com/jdg) for building [MBProgressHUD](https://github.com/jdg/MBProgressHUD) - all my ideas and many implementation details were provided by his library.

This HUD does not use any [data](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests) or [API](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api) from the privacy manifest. And it's not on this [list](https://developer.apple.com/support/third-party-SDK-requirements) either.

If you are interested, please browse and provide valuable feedback.

**Comment by brendand** [comment]
@liam-i Will your Swift implementation also work from Objective-C?

**Comment by liam-i** [comment]
> @liam-i Will your Swift implementation also work from Objective-C?

Cannot run directly on Objective-C. But bridging is possible, please refer to the [HUD-Bridging-OC](https://github.com/liam-i/HUD/blob/main/Example/HUD-Bridging-OC.swift) and [OCPresentViewController.m](https://github.com/liam-i/HUD/blob/main/Example/OCPresentViewController.m) files.

**Comment by nmendiratta89** [comment]
+1

**Comment by frankiebarrios** [comment]
+1

**Comment by theLittleApps** [comment]
+1

**Comment by percival888** [comment]
+1

**Comment by shsw228** [comment]
+1

**Comment by RideShi** [comment]
+1

**Comment by MrMage** [comment]
Instead of replying with +1, could everyone please just press the "thumbs up" emoji on the original post and subscribe to notifications in the sidebar? If you post a "+1", everyone who is already subscribed to this thread gets an unneccessary notification.

**Comment by manahilov** [comment]
> I made a Swift version of the HUD. https://github.com/liam-i/FlyHUD
> 
> Thanks a lot to [Jonathan George](https://github.com/jdg) for building [MBProgressHUD](https://github.com/jdg/MBProgressHUD) - all my ideas and many implementation details were provided by his library.
> 
> This HUD does not use any [data](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests) or [API](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api) from the privacy manifest. And it's not on this [list](https://developer.apple.com/support/third-party-SDK-requirements) either.
> 
> If you are interested, please browse and provide valuable feedback.

Actually it is on the list - https://developer.apple.com/support/third-party-SDK-requirements, why I don't know. Just went trough the source and indeed it is not using any of the described APIs..

**Comment by percival888** [comment]
According to Apple's requirements, even if the APIs that needs to be explained are not used, it's need to include a manifest to declare that they're not using any of the affected APIs or tracking anything. However, they must include such a file regardless.

**Comment by jdg** [comment]
merged, thanks!

**Comment by matrejek** [comment]
@jdg would there be a chance to add new version tag on this change? It's obviously possible to target specific revision but targeting tag/version seems way cleaner :)

**Comment by manahilov** [comment]
Can someone open a PR with updated Swift package?
```
// swift-tools-version:5.9
import PackageDescription

let package = Package(
    name: "MBProgressHUD",
    products: [
        .library(name: "MBProgressHUD", targets: ["MBProgressHUD"])
    ],
    targets: [
        .target(
            name: "MBProgressHUD",
            dependencies: [],
            path: ".",
            exclude: ["Demo"],
            sources: ["MBProgressHUD.h", "MBProgressHUD.m"],
            resources: [.copy("PrivacyInfo.xcprivacy")],
            publicHeadersPath: "include"
        )
    ]
)

````

That should include the Privacy manifest when consuming the framework via SPM.
I don't have permissions to create a PR.

Thank you in advance.

**Comment by matrejek** [comment]
I have opened #653 with the change as suggested by @manahilov - @jdg - could you have a look?
