### ISSUE TITLE
HUD Scrolls with UITableView and gets clipped underneath TableViewHeaders

### ISSUE THREAD

**Issue by besi** [jdg/MBProgressHUD#74]
I put a loader ontop of a UITableView like so:

```
- (void) showLoadingOverlay{
    [MBProgressHUD showHUDAddedTo:self.view animated:YES];
}
```

Now when the spinner is shown and I scroll the UITableView, then the UITableView scrolls with it and the HUD gets clipped underneath the TableViewHeader.

**Comment by icamchu** [comment]
Add to UIWindow

 MBProgressHUD *hud = [MBProgressHUD showHUDAddedTo:[UIApplication sharedApplication].delegate.window animated:YES];
