### ISSUE TITLE
multiline for labelText property required (again)

### ISSUE THREAD

**Issue by benrudhart** [jdg/MBProgressHUD#80]
this feature was available earlier and I would love to have it back!

A good solution would add a property (BOOL) like textLabelMultiline, or property (int) textLabelNumberOfLines

otherwise the textLabel itself could be made public so that the numberOfLines can be set (and treated in layoutSubviews)

**Comment by besi** [comment]
+1

![screen shot 2015-06-05 at 10 11 30](https://cloud.githubusercontent.com/assets/160412/8001969/478a6494-0b6b-11e5-889c-6a70da55f30b.png)

**Comment by besi** [comment]
This is actually possible when you use detailLabelText:

http://stackoverflow.com/a/15031656/784318

**Comment by besi** [comment]
@benrudhart I am just using the detailTextLabel for this reason. 
Also see <http://stackoverflow.com/a/15031656/784318>
